
[audio]
; source: edition and episode
source = b:ep01
g_debut=0:2660,silence=0.5,gain=4

# Décommenter ces lignes pour utiliser l'audio de l'édition k
; source = k:ep01
; g_debut=0:2665,silence=1


[video]
; edition et épisode par défaut
ed_ref = f
source = s0:ep01

[shots]
# ici, abus de langage: netteté = finesse des traits

000= ep=1, ed=f
# 2023-04-16: f > s:2 > s0 s:2 a trop de fourmillements

001= ep=1, ed=s0
# 2023-04-16:  s0 > s:02 > f plus de détails nets

002= ep=2, ed=s
# 2023-04-16: s:02 > k:01

003= ep=1, ed=f
# 2023-04-16: f > k

004= ep=1, ed=f
# 2023-04-16: f > k mais moins plus jaune

005= ep=1, ed=f
# 2023-04-16: f (08e1750) meilleur que s0 mais plus jaune
; bilateralFilter=11:15:13, unsharp_mask=2:0.3;

006= ep=1, ed=k
# 2023-04-16: k: meilleure définition et cadrage pas très important

007= ep=1, ed=f
# 2023-04-16: f > s > s0, sauf pour la colorimétrie

008= ep=1, ed=f
# 2023-04-16: f > k, mais très légèrement (finesse du trait selon les trames)

009= ep=1, ed=f
# 2023-04-16: f > s0 > s, sauf colorimétrie (k, bavures bleues sur la peau)

010= ep=1, ed=f
# 2023-04-16: f > k > s0, sauf colorimétrie, k pouraait être meilleure mais
# trop de bruit sur les contours de l'image et cadrage

011= ep=1, ed=f
# 2023-04-16: f > k sauf colorimétrie

012= ep=1, ed=k
# 2023-04-16: k > s0

013= ep=2, ed=s



