
[audio]
; source: edition and episode
source = b:ep01
g_debut=0:2660,silence=1

# Uncomment the following lines to use the k edition (mono)
; source = k:ep01
; g_debut=0:2665,silence=1

[video]
; default source for this generique, may be overwritten in the list of shots
; warning: the episode is used the reference for calcualtion of offsets
; due to g_fin whose shots are not defined in edition k
ed_ref = k
source = k:ep01
shots=
        0:648, ep=1, ed=k
      648:798, ep=1, ed=k
     798:1086, ep=1, ed=k
    1086:1297, ep=1, ed=k
    1297:1508, ep=1, ed=k
    1508:1632, ep=1, ed=k
    1632:1796, ep=1, ed=k
    1796:1877, ep=1, ed=k
    1877:1914, ep=1, ed=k
    1914:1955, ep=1, ed=k
    1955:2003, ep=1, ed=k
    2003:2198, ep=1, ed=k
    2198:2630, ep=1, ed=k

# poc 2021:
#   0:1087 -> s:ep02
#  1088:2630 -> s:ep01

[frames]
frames=
      40, ep=1, ed=k
     125, ep=1, ed=k
     285, ep=1, ed=k
     365, ep=1, ed=k
     530, ep=1, ed=k
     620, ep=1, ed=k
     641, ep=1, ed=k
     735, ep=1, ed=k
     750, ep=1, ed=k
     795, ep=1, ed=k
     798, ep=1, ed=k
     870, ep=1, ed=k
    1025, ep=1, ed=k
    1080, ep=1, ed=k
    1087, ep=1, ed=k
    1130, ep=1, ed=k
    1138, ep=1, ed=k
    1223, ep=1, ed=k
    1302, ep=1, ed=k
    1373, ep=1, ed=k
    1435, ep=1, ed=k
    1491, ep=1, ed=k
    1520, ep=1, ed=k
    1573, ep=1, ed=k
    1616, ep=1, ed=k
    1687, ep=1, ed=k
    1741, ep=1, ed=k
    1756, ep=1, ed=k
    1785, ep=1, ed=k
    1853, ep=1, ed=k
    1880, ep=1, ed=k
    1903, ep=1, ed=k
    1938, ep=1, ed=k
    1993, ep=1, ed=k
    2060, ep=1, ed=k
    2158, ep=1, ed=k
    2177, ep=1, ed=k
    2199, ep=1, ed=k
    2238, ep=1, ed=k
    2266, ep=1, ed=k
    2293, ep=1, ed=k
    2346, ep=1, ed=k
    2519, ep=1, ed=k
    2520, ep=1, ed=k
    2521, ep=1, ed=k
    2588, ep=1, ed=k



; [frames]
; frames=
;       40, ep=2, ed=s
;      125, ep=2, ed=s
;      285, ep=2, ed=s
;      365, ep=2, ed=s
;      530, ep=2, ed=s
;      620, ep=2, ed=s
;      641, ep=2, ed=s
;      735, ep=2, ed=s
;      750, ep=2, ed=s
;      795, ep=2, ed=s
;      798, ep=2, ed=s
;      870, ep=2, ed=s
;     1025, ep=2, ed=s
;     1080, ep=1, ed=k
;     1087, ep=2, ed=s
;     1130, ep=2, ed=s
;     1138, ep=2, ed=s
;     1223, ep=2, ed=s
;     1302, ep=2, ed=s
;     1373, ep=2, ed=s
;     1435, ep=2, ed=s
;     1491, ep=2, ed=s
;     1520, ep=2, ed=s
;     1573, ep=2, ed=s
;     1616, ep=2, ed=s
;     1687, ep=2, ed=s
;     1741, ep=2, ed=s
;     1756, ep=2, ed=s
;     1785, ep=2, ed=s
;     1853, ep=2, ed=s
;     1880, ep=2, ed=s
;     1903, ep=2, ed=s
;     1938, ep=2, ed=s
;     1993, ep=2, ed=s
;     2060, ep=2, ed=s
;     2158, ep=2, ed=s
;     2177, ep=2, ed=s
;     2199, ep=2, ed=s
;     2238, ep=2, ed=s
;     2266, ep=2, ed=s
;     2293, ep=2, ed=s
;     2346, ep=2, ed=s
;     2519, ep=2, ed=s
;     2520, ep=2, ed=s
;     2521, ep=2, ed=s
;     2588, ep=2, ed=s

; These 2 frames are used to verify offsets of this part
; They correspons to the last frame of a shot and to the first frame of the following shot:
    ; 1296, ep=2, ed=s
    ; 1297, ep=2, ed=s
