
; [filters_g_debut]

; # Upscale with opencv
; id_pre_upscale=9
; pre_upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic
;     """


; id_upscale=9
; upscale="""
;     scale=width_upscale:height_upscale:bicubic
;     """


; id_denoise=9
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     unsharp_mask=3:1.2
;     """


; id_sharpen=9
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.3,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """




# Upscale with ffmpeg
; id_upscale=8
; upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic,
;     scale=width_upscale:height_upscale:sws_flags=bicubic+accurate_rnd+bitexact+full_chroma_int,
;     setsar=1,setdar=1
;     """

; id_denoise=8
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     unsharp_mask=3:1.2
;     """


; id_sharpen=18
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.3,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """





; id_upscale=0
; upscale_ffmpeg="""
;     scale=width_upscale:height_upscale:sws_flags=lanczos+accurate_rnd+bitexact+full_chroma_int,
;     setsar=1,setdar=1
;     """

; pas de différences entre bicubic et lanczos

; id_upscale=1
; 41s
; upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic,
;     scale=width_upscale:height_upscale:sws_flags=lanczos+accurate_rnd+bitexact+full_chroma_int,
;     setsar=1,setdar=1
;     """

; id_upscale=2
; upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic,
;     scale=width_upscale:height_upscale:sws_flags=bicubic+accurate_rnd+bitexact+full_chroma_int,
;     setsar=1,setdar=1
;     """

; id_upscale=3
; flou
; upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic,
;     scale=width_upscale:height_upscale:sws_flags=gauss+accurate_rnd+bitexact+full_chroma_int,
;     setsar=1,setdar=1
;     """

