
[audio]
; source: edition and episode
source = b:ep01
g_debut=0:2660,silence=0.5,gain=4

# Uncomment the following lines to use the k edition (mono)
; source = k:ep01
; g_debut=0:2665,silence=1

[video]
; edition et épisode par défaut
ed_ref = s0
source = s0:ep01

[shots]
# ici, abus de langage: netteté = finesse des traits

000= ep=2, ed=s
# s0 est plus nette mais plus de fourmillements

001= ep=1, ed=s0
# s0 a plus de sintillements nets, k pourrait être très bien

002= ep=2, ed=s
# plus lumineux

003= ep=1, ed=s
# s plus stable

004= ep=1, ed=s
# S fourmille moins que s0

005= ep=1, ed=s
# s a moins de bruit que s0

006= ep=1, ed=k
# k: meilleure définition et cadrage pas très important

007= ep=1, ed=s
# s0 est très légèrement plus net mais a plus de fourmillements

008= ep=1, ed=k

009= ep=1, ed=s

010= ep=1, ed=s0
# k  serait meilleure mais trop de bruit sur les contours de l'image
# et cadre trop serré

011= ep=1, ed=s
# k  serait meilleure mais trop de bruit sur les contours de l'image
# s est légèrement moins net (à voir après correction colorimétrique)

012= ep=2, ed=s
# Changer par s0 si la correctoin de la colorimétrie n'est pas bonne


; [shots]
; 000=        0:648, ep=1, ed=s0
; 001=      648:798, ep=1, ed=s0
; 002=     798:1086, ep=1, ed=s0
; 003=    1086:1297, ep=1, ed=s0
; 004=    1297:1508, ep=1, ed=s0
; 005=    1508:1632, ep=1, ed=s0
; 006=    1632:1796, ep=1, ed=s0
; 007=    1796:1877, ep=1, ed=s0
; 008=    1877:1914, ep=1, ed=s0
; 009=    1914:1955, ep=1, ed=s0
; 010=    1955:2003, ep=1, ed=s0
; 011=    2003:2198, ep=1, ed=s0
; 012=    2198:2630, ep=1, ed=s0


# poc 2021:
#   0:1087 -> s:ep02
#  1088:2630 -> s:ep01
