
[audio.fr]
source = k
precedemment = 2659:3390
episode = 3390:33479, fadeout=0.50:cos, silence=0.5
g_asuivre = 33480:33553
asuivre = 33553:34197, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34198:34466
documentaire = 34466:38855, fadeout=0.25:cos, silence=0.5


[audio.en]
source = f
precedemment = 2698:3429
episode = 3429:33519, silence=0.5
g_asuivre = 33519:33593
asuivre = 33593:34238, fadeout=2.0:cos, silence=0.5
g_documentaire =
    34252:34266
    34252:34505
documentaire = 34505:38897, fadeout=1.0:cos, silence=0.5


[video]
source = f

; [video.fr]
; source = k
; precedemment  = 2664:3377
; episode = 3390:-1
; ; g_asuivre =
; asuivre = 33553:-1
; ; g_documentaire =
; documentaire = 34466:38855, fadeout=1.0

