[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2700:3416
episode = 3431:33509
g_asuivre = 33517:33593
asuivre = 33593:34191
g_documentaire = 34237:34504
documentaire = 34505:38894


[shots_precedemment]
000 = 2700:3416
; 2806

[shots_episode]
000 = 3431:33509
; 3705

[shots_asuivre]
000 = 33593:34191
; 33645

[shots_documentaire]
000 = 34505:38894
