; [filters]
; id_pre_upscale=6
; pre_upscale_ffmpeg="nlmeans"

; id_upscale=6
; upscale_ffmpeg="""
;     scale=width_upscale:height_upscale:gauss+accurate_rnd+bitexact,
;     spp=4:10,
;     unsharp=13:13:2.8, nlmeans=s=1.2,
;     unsharp=7:7:1.5, nlmeans=s=1
;     """

; id_denoise=6
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:15,
;     """

; id_sharpen=6
; sharpen="""
;     unsharp=7:7:1.5, nlmeans=s=1,
;     """


[offsets]
g_debut=0:0
g_documentaire=0:-1315
g_fin=0:-2196

