[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    pytorch:    2x_LD-Anime_Compact_330k_net_g;
    *pytorch:    1x_HurrDeblur_SuperUltraCompact_nf24-nc8_244k_net_g;
    python:     scale=0.5:bicubic;
    *pytorch:    realesr-animevideov3;
    python:     scale=0.5:bicubic;
    python:     deshake;
    ffmpeg:     hqdn3d=0:0:6:6;
    python:     unsharp_mask=2:0.3;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    pytorch:    2x_LD-Anime_Compact_330k_net_g;
    *pytorch:    1x_HurrDeblur_SuperUltraCompact_nf24-nc8_244k_net_g;
    python:     scale=0.5:bicubic;
    *pytorch:    realesr-animevideov3;
    python:     scale=0.5:bicubic;
    python:     deshake;
    ffmpeg:     hqdn3d=0:0:6:6;
    python:     unsharp_mask=2:0.3;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    pytorch:    2x_LD-Anime_Compact_330k_net_g;
    *pytorch:    1x_HurrDeblur_SuperUltraCompact_nf24-nc8_244k_net_g;
    python:     scale=0.5:bicubic;
    *pytorch:    realesr-animevideov3;
    python:     scale=0.5:bicubic;
    python:     deshake;
    ffmpeg:     hqdn3d=0:0:6:6;
    python:     unsharp_mask=2:0.3;
    """


[parts]
; ko:
g_debut=0:2670
precedemment=2703:3415
episode=3415:34892
g_asuivre=34904:34976
asuivre=34976:35604

; ok:
g_reportage=37078:37346
reportage=37346:41141
g_fin=41152:42958


; [shots_precedemment]
; [shots_episode]
; [shots_asuivre]
; [shots_reportage]
