
[audio.fr]
source = k
precedemment = 2663:3371
episode = 3371:33560, fadeout=0.25:cos, silence=0.5
g_asuivre = 33566:33637
asuivre = 33637:34287, fadeout=0.50:cos, silence=0.5
g_documentaire =
    34302:34316
    34302:34554
documentaire = 34554:38818, silence=0.5


[audio.en]
source = f
precedemment = 2693:3418
episode = 3418:33618, fadeout=0.5:cos, silence=0.5
g_asuivre = 33621:33693
asuivre = 33693:34342, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34357:34371
    34357:34609
documentaire = 34609:38890, fadeout=0.25:cos, silence=0.5


[video]
source = f

; [video.fr]
; source = k
; precedemment  = 2664:3360
; episode = 3369:-1
; ; g_asuivre =
; asuivre = 33637:-1
; ; g_documentaire =
documentaire = fadeout=1.0


