[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2694:3408
episode = 3425:33510
g_asuivre = 33619:33693
asuivre = 33694:34259
g_documentaire = 34340:34608
documentaire = 34609:38902


[shots_precedemment]
000 = 2694:3408
; 2782

[shots_episode]
000 = 3425:33510
; 3701

[shots_asuivre]
000 = 33694:34259
; 33752

[shots_documentaire]
000 = 34609:38902
