[audio]
# Not validated
source = k
precedemment = 2667:3373
episode = 3373:34852, fadeout=0.3:log, silence=0.5
g_asuivre = 34861:34861
asuivre = 34933:35583, silence=0.5
g_reportage =
    35583:35848
reportage = 35848:39249, fadeout=0.3:cos, silence=0.5


[video]
# Not validated
precedemment = 2666:3371
episode = 3381:-1
; g_asuivre =
asuivre = 34933:-1
; g_reportage =
reportage = 35849:39254, fadeout=1.0

