[audio.fr]
# Use the B edition (stereo)
source = b:ep01
g_fin = 38673:40575, avsync=0.5, silence=0.5, gain=3


# Uncomment these lines to use the k edition (mono)
; source = k:ep01
; g_fin=
;     868:80.171, avsync=0.5
;     1591.822:1596.390, gain=0.5
;     80.171:2666, silence=0.8

[audio.en]
# Use the B edition (stereo)
source = f:ep01
g_fin = 40128:41941, silence=0.5


[video]
; source = f:ep01
source = f:ep11
; source = s:ep11
g_fin = fadeout=2.0


# English is not the same! shorter
; missing 39911 -> 40043 to put @39194


# shots:
#   3: nlmeans + AnimeSR_v2 + BeaverIt
#   4: nlmeans + AnimeSR_v2 + BeaverIt
#   6: nlmeans + AnimeSR_v2 + BeaverIt
#   11: nlmeans + AnimeSR_v2 + BeaverIt


