
[audio]
; reference_edition=k
; reference_episode=11
; # extract this segment from the referenced edition/episode
; g_fin=38875:40775,avsync=0.5
reference_edition=k
reference_episode=1
g_fin=
    868:80.171, avsync=0.5
    1591.822:1596.390, gain=0.5
    80.171:2666, silence=0.8

; [audio]
; reference=s
; g_fin=38878:40625


[video]
reference_edition=s
reference_episode=11
shots=
    38882:39194, ep=11, ed=s
    39194:39648, ep=11, ed=s
    39648:39696, ep=11, ed=s
    39696:39720, ep=11, ed=s
    39720:39742, ep=11, ed=s
    39742:39818, ep=11, ed=s
    39818:39857, ep=11, ed=s
    39857:39913, ep=11, ed=s
    39913:40208, ep=11, ed=s
    40208:40512, ep=11, ed=s
    40512:40812, ep=11, ed=s



[frames]
# Ces numéros de trames sont basées sur l'édition spécifiée
# De plus, le no. réel de trame dans cet épisode est corrigé avec l'offset
# défini dans chaque épisode
reference="s"
reference_episode=1
frames=
    38735, ep=11
    38799, ep=11
    39069, ep=11
    39237, ep=11
    39456, ep=11
    39615, ep=11
    39649, ep=11
    39660, ep=11
    39677, ep=11
    39748, ep=11
    39994, ep=11
    40029, ep=11
    40209, ep=11
    40495, ep=11



# Enable this for comparisons between editions
# L'épisode 11 est le meilleur tant au niveau cadrage qu'au
# niveau colorimétrie
; g_fin=
;    *:38735
;    *:38799
;    *:39069
;    *:39237
;    *:39456
;    *:39615
;    *:39649
;    *:39660
;    *:39677
;    *:39748
;    *:39994
;    *:40029
;    *:40209
;    *:40495

