[audio]
# Use the B edition (stereo)
source = b:ep01
g_fin = 38673:40575, avsync=0.5, silence=0.5, gain=3


# Uncomment these lines to use the k edition (mono)
; source = k:ep01
; g_fin=
;     868:80.171, avsync=0.5
;     1591.822:1596.390, gain=0.5
;     80.171:2666, silence=0.8


[video]
ed_ref = s
source = s:ep11

