[s.ep11.g_fin]
; 38882
; 39171
39192_deshake="""enable=true;
    cv2_deshaker:start=45:end=364:ref=end:mode=vertical;
    cv2_deshaker:start=364:end=454:ref=start:mode=translation;
    """
39646_deshake="enable=true;cv2_deshaker:start=0:end=48:ref=start:mode=translation;"
39694_deshake="enable=true;cv2_deshaker:start=0:end=24:ref=start:mode=translation;"
; 39718
39740_deshake="""enable=true;
    cv2_deshaker:start=0:end=42:ref=start:mode=vertical;
    """
39816_deshake="enable=false;cv2_deshaker:start=0:end=39:ref=start:mode=translation;"
39855_deshake="enable=true;cv2_deshaker:start=0:end=56:ref=start:mode=translation;"
39911_deshake="""enable=true;
    cv2_deshaker:start=0:end=132:ref=start:mode=vertical;
    cv2_deshaker:start=132:end=207:ref=start:mode=translation;
    cv2_deshaker:start=207:end=219:ref=start:mode=translation;
    cv2_deshaker:start=219:end=295:ref=start:mode=translation;
    """
40206_deshake="""enable=true;
    cv2_deshaker:start=0:end=292:ref=start:mode=vertical;
    """
40510_deshake = """enable=true;
    cv2_deshaker:start=0:end=51:ref=start:mode=vertical;
    cv2_deshaker:start=51:end=102:ref=start:mode=vertical;
    cv2_deshaker:start=102:end=302:ref=start:mode=vertical;
    """