
[audio.fr]
source = b:ep01
g_debut =  0:2660, avsync=0.25, silence=0.5, gain=4
# Décommenter ces lignes pour utiliser l'audio de l'édition k
; source = k:ep01
; g_debut = 0:2665,silence=1


[audio.en]
source = f:ep02
g_debut = 25:2685, silence=0.5


[video]
source = j:ep99
g_debut = fadeout=2


[scenes]
max = 14

000 = ep=99, ed=j, scene=0, segment=14:660
001 = ep=99, ed=j, scene=1, segment=690:140
; zoom in, during count frames, zoom factor from 0.2 to 1, then loop, then fadeout
002 = ep=99, ed=j, scene=2,
    effect=zoom_in:-1:125:1.25,
    effect=title:20:2.8:0.75
; blend with the last frame of the last scene
003 = ep=99, ed=j, scene=4,
    segment=1100:40,
    effect=blend:25,
    effect=title:-1:0.75:0.75
004 = ep=99, ed=j, scene=5, segment=1363:210
005 = ep=99, ed=j, scene=6, segment=1580:212
006 = ep=99, ed=j, scene=7, segment=1798:128
007 = ep=99, ed=j, scene=8, segment=1930:166
008 = ep=99, ed=j, scene=9
009 = ep=99, ed=j, scene=11, segment=2257:40
010 = ep=99, ed=j, scene=13,
011 = ep=99, ed=j, scene=15, segment=2698:48
012 = ep=99, ed=j, scene=16, segment=2754:195
013 = ep=99, ed=j, scene=17
014 = ep=99, ed=j, scene=18,
    segment=3278:1,
    effect=title:25:0.35:0.75
