
[audio.fr]
; source: edition and episode
source = b:ep01
g_debut =  0:2660, silence=0.5, gain=4
# Décommenter ces lignes pour utiliser l'audio de l'édition k
; source = k:ep01
; g_debut = 0:2665,silence=1

[audio.en]
source = f:ep02
g_debut = 25:2685, silence=0.5


[video]
; default edition:episode used if not specified in the list of scenes
source = j:ep01
g_debut = fadeout=3.0

; [scenes.en]
; use default scenes

[scenes.fr]
000= ep=99, ed=j, scene=0
001= ep=99, ed=j, scene=1
002= ep=99, ed=j, scene=2
; 003= ep=99, ed=j, scene=3, segment=...:.., zoom_in=count:zoom, logo=out:count:factor_start
003= ep=2, ed=s, scene=3
; 004= ep=1, ed=j, scene=5, segment=1260:254
004= ep=99, ed=j, scene=4
005= ep=99, ed=j, scene=5, segment=1363:214
; 005= scene=5, segment=1515:210
006= ep=99, ed=j, scene=6
007= ep=99, ed=j, scene=7
008= ep=99, ed=j, scene=8
009= ep=99, ed=j, scene=9
010= ep=99, ed=j, scene=11
011= ep=99, ed=j, scene=13
012= ep=99, ed=j, scene=15
013= ep=99, ed=j, scene=16
014= ep=99, ed=j, scene=17
; 014= ep=99, ed=j, scene=17, effect, logo=out:count:factor_start


; [scenes.fr]
; 000= ep=1, ed=f
; 001= ep=1, ed=f
; 002= ep=2, ed=s
; 003= ep=2, ed=s
; 004= ep=1, ed=f
; 005= ep=1, ed=f
; 006= ep=1, ed=f
; 007= ep=1, ed=f
; 008= ep=1, ed=f
; 009= ep=1, ed=f
; 010= ep=1, ed=f
; 011= ep=1, ed=f
; 012= ep=1, ed=f
; 013= ep=2, ed=s
; 014= ep=2, ed=s


; [scenes.fr]
; 2661 frames

; 000= ep=1, ed=f
; # 2023-04-16: f > s:ep02 > s0. s:ep02 a trop de fourmillements
; # 2023-04-22:
; #   f: animesr > real-cugan: mais plus flou, moins d'étoiles,
; #               plus agréable, lors du zoom sur la terre
; #   -> f, animesr


; 001= ep=1, ed=f
; # 2023-04-16:  s0 > s:ep02 > f plus de détails nets
; # 2023-04-22:
; #   - s0: real-cugan vs animesr: plus net mais trop de halo, rendre real-cugan plus net?
; #   - f: real-cugan vs animesr: plus net mais trop de halo -> animesr
; #   - s: animesr: trop flou -> real-cugan
; #   - s:ep2: real-cugan > animesr
; #   - k: real-cugan vs animesr: plus net mais trop de halo -> animesr
; #   - f (animesr) > k > s > s2
; #   -> f, animesr


; 002= ep=2, ed=s
; # 2023-04-16: s:ep02 > k
; # 2023-04-22: séparé en 2 scenes
; # scene 2.0
; #   k: cugan vs animesr: plus net mais fourmille plus
; #   s:ep2  : cugan > animesr
; #   k plus agréable mais trop de bruit sur le côté gauche
; #   -> s:ep2 cugan
; # 2024-07-15
; #   s:02 b63284f
; #   scunet_color_real_gan:trt:fp16
; #   pro-no-denoise-up2x:trt:fp16

; 003= ep=2, ed=s
; # scene 2.1, devenue scene 3
; #   s:ep2  : animesr > cugan
; #   k:  animesr vs cugan: logo meilleur, mois de halo
; #       mais trop de fourmillements en arrière plan
; #   s:ep2 > k: moins de bruit sur bord gauche et moins de fourmillements
; #               même si logo un peu moins bon
; #   -> s:ep2, animesr
; # 2024-07-15
; #   s:02 b63284f
; #   scunet_color_real_gan:trt:fp16
; #   pro-no-denoise-up2x:trt:fp16

; 004= ep=1, ed=f
; # 2023-04-16: f > k
; # 2023-04-22: f: animesr > real-cugan
; #   -> f, real-cugan


; 005= ep=1, ed=f
; # 2023-04-16: f > k mais plus jaune
; # 2023-04-22: f: animesr ~= real-cugan: légèrement plus flou, moins de détails
; #               mais meilleur sur les nuages. choix de real-cugan
; #   -> f, real-cugan


; 006= ep=1, ed=f
; # 2023-04-16: f (08e1750) meilleur que s0 mais plus jaune
; ;               bilateralFilter=11:15:13, unsharp_mask=2:0.3;
; # 2023-04-22: f: animesr > real-cugan: plus flou mais moins bruit, traits mieux définis
; #               au premier plan
; #   -> f, animesr


; 007= ep=1, ed=f
; # 2023-04-16: k: meilleure définition et cadrage pas très important
; # 2023-04-22: k: real-cugan n3 > animesr
; #   -> k, real-cugan
; # 2024-07-15
; # 2x_Pooh_V4_Candidate_2_422k

; 008= ep=1, ed=f
; # 2023-04-16: f > s > s0, sauf pour la colorimétrie
; # 2023-04-22: f: real-cugan n3 > animesr: traits légèrements meilleurs
; #   -> f, real-cugan


; 009= ep=1, ed=f
; # 2023-04-16: f > k, mais très légèrement (finesse du trait selon les trames)
; # 2023-04-22: f: animesr > real-cugan: plus flou en arrière plan mais plus naturel,
; #               traits mieux défini en premier plan
; #   -> f, animesr


; 010= ep=1, ed=f
; # 2023-04-16: f > s0 > s, sauf colorimétrie (k, bavures bleues sur la peau)
; # 2023-04-22: f: animesr > real-cugan: plus flou en arrière plan mais plus naturel,
; #               traits mieux défini en premier plan
; #   -> f, animesr


; 011= ep=1, ed=f
; # 2023-04-16: f > k > s0, sauf colorimétrie, k pouraait être meilleure mais
; #               trop de bruit sur les contours de l'image et cadrage
; # 2023-04-22: f: animesr > real-cugan: plus flou en arrière plan mais plus naturel,
; #               traits mieux défini en premier plan.
; #               f(animesr) vs k(real-cugan): k est plus net mais fourmille plus (trop)
; #   -> f, animesr


; 012= ep=1, ed=f
; # 2023-04-16: f > k sauf colorimétrie
; # 2023-04-22: f:real-cugan > animesr. f vs k: est plus naturel (moins de halo sur les traits)
; #               même si moins net
; #   -> f, real-cugan


; 013= ep=2, ed=s
; # 2023-04-16: !!! k > s0 > s:ep02, mais choix de s:ep02 à cause du scene no. 13
; # 2023-04-22:
; #   - k: animesr > real-cugan: moins de halo, traits mieux définis, soleil plus naturel
; #   - s0: animesr vs real-cugan: bcp plus flou, bruité, mais plus "naturel" sur le soleil
; #   - k > s0: plus net, moins de halo
; #   - s:ep2: animesr vs real-cugan: plus de détails, mais bcp plus bruité, légèrement moins de halo
; #   - s:ep02 vs k: moins net mais soleil meilleur, colorimétrie moins bonne
; #   -> choix de s:ep02(real-cugan) le plus acceptable mais par dépit...
; # 2024-07-15
; #   s:02 b63284f
; #   scunet_color_real_gan:trt:fp16
; #   pro-no-denoise-up2x:trt:fp16

; 014= ep=2, ed=s
; # 2023-04-16: s:ep02 > k. probleme diff de colorimétrie/zoom entre 012/013.
; #                       soit trouver la bonne colorimétrie pour éviter trop de diff + zoom
; #                       soit fade entre les 2 segments + zoom : non, trop couteux en temps/complexité
; #                       soit bonne colorimétrie sur scene 12 pour s:ep02
; # 2023-04-22:
; #   - k: animesr > real-cugan: moins de halo, traits mieux définis
; #   - s: animesr vs real-cugan: plus de détails, mais plus bruité, moins de halo
; #   - s0: animesr vs real-cugan: plus de détails, mais plus bruité, moins de halo
; #   - s:ep2: animesr vs real-cugan: plus de détails, mais plus bruité, plus flou, moins de halo
; #   -> choix de s:ep02(real-cugan) le plus acceptable mais par dépit...
; # 2024-07-15
; #   s:02 b63284f
; #   scunet_color_real_gan:trt:fp16
; #   pro-no-denoise-up2x:trt:fp16
