

[frames]
offsets_g_debut=0:0
offsets_precedemment=0:25
offsets_episode=0:25
offsets_asuivre=0:25
offsets_reportage=0:25
# vs ed:ep defined as reference
offsets_g_reportage=0:294
offsets_g_fin=0:-337

