# fadeout is in seconds
# silence is in seconds

[audio]
; used as the source and the target, because it is the best edition.
source = k
precedemment = 0:0
episode = 2698:33808, fadeout=1.0:cos, silence=0.5
g_asuivre =33811:33878
asuivre = 33878:34583, silence=0.5
g_reportage =
    34597:34612
    34597:34850
reportage = 34850:38674, fadeout=0.5:log, silence=0.5


[video]
; used to define the target,
; the reference for the frame no. is the edition defined in common.ini
precedemment = 0:0
episode = 2672:-1
; g_asuivre =
asuivre = 33878:-1, fadeout=0.5
; g_reportage =
reportage = 34850:38674, fadeout=1.0





[stitching]
; This option is used to define the edition used as the background
; when stitching the images
; Note for later: may be overwritten if shots uses different editions for the stitching???
bgd = f




; [filters_episode]
; # this is the common filter used after having merged the background and the foreground images
; # 2022-04-22: just changed indice for homography comparisons
; # 2022-03-30
; id_sharpen=3
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     brightness_contrast=255:130
;     """



; meilleur que 501 mais légèrement plus flou, plus net que 507
; id_sharpen=11
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     brightness_contrast=255:130
;     """


; id_sharpen=10
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:0.4
;     """




; meilleur que 501 mais légèrement plus flou
; id_sharpen=7
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:0.7,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """




; id_sharpen=7
; sharpen="""
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.5,
;     bilateralFilter=11:15:13,
;     morphologyEx=MORPH_RECT:3:1
;     """

; id_sharpen=6
; sharpen="""
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:0.2
;     """

; id_sharpen=4
; sharpen="""
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:1,
;     """

; id_sharpen=4
; sharpen="""
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """


; id_sharpen=3
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1
;     """

; id_sharpen=2
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1
;     """


; id_sharpen=1
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:0.7,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:1.1,
;     morphologyEx=MORPH_RECT:3:1
;     """


; [parts]
; precedemment=0:0
; episode=4628:35764
; g_asuivre=35769:35837
; asuivre=35837:36534
; g_reportage=36538:36808
; reportage=36808:40633


[frames]

; episode=
;      3675

; episode=
;     6069
;     6070
;     6071
;     6072
;     6073
;     6074
;     6075
;     6076
;     6077
;     6078
;     6079
;     6080
;     6081
;     6082
;     6083
;     6084
;     6085
;     6086
;     6087
;     6088
;     6089
;     6090
;     6091
;     6092
;     6093
;     6094
;     6095
;     6096
;     6097
;     6098
;     6099
;     6100
;     6101
;     6102
;     6103
;     6104
;     6105
;     6106
;     6107
;     6108
;     6109
;     6110
;     6111
;     6112
;     6113
;     6114
;     6115
;     6116
;     6117
;     6118
;     6119
;     6120
;     6121
;     6122
;     6123
;     6124
;     6125
;     6126
;     6127
;     6128
;     6129
;     6130
;     6131
;     6132
;     6133
;     6134


; episode=
;     5986
;     5987
;     5988
;     5989
;     5990
;     5991
;     5992
;     5993
;     5994
;     5995
;     5996
;     5997
;     5998
;     5999
;     6000
;     6001
;     6002
;     6003
;     6004
;     6005
;     6006
;     6007
;     6008
;     6009
;     6010
;     6011
;     6012
;     6013
;     6014
;     6015
;     6016
;     6017
;     6018
;     6019
;     6020
;     6021
;     6022
;     6023
;     6024
;     6025
;     6026
;     6027
;     6028
;     6029
;     6030
;     6031
;     6032
;     6033
;     6034
;     6035
;     6036
;     6037
;     6038
;     6039
;     6040
;     6041
;     6042
;     6043
;     6044
;     6045
;     6046
;     6047
;     6048
;     6049
;     6050
;     6051
;     6052
;     6053
;     6054
;     6055
;     6056
;     6057
;     6058
;     6059
;     6060
;     6061
;     6062
;     6063
;     6064
;     6065
;     6066
;     6067
;     6068



    ; 4309
    ; 4310
    ; 4311
    ; 4312
    ; 4313
    ; 4314
    ; 4315
    ; 4316
    ; 4317
    ; 4318
    ; 4319
    ; 4320
    ; 4321
    ; 4322
    ; 4323
    ; 4324
    ; 4325
    ; 4326
    ; 4327
    ; 4328
    ; 4329
    ; 4330
    ; 4331
    ; 4332
    ; 4333
    ; 4334
    ; 4335
    ; 4336
    ; 4337
    ; 4338
    ; 4339
    ; 4340
    ; 4341
    ; 4342
    ; 4343
    ; 4344
    ; 4345
    ; 4346
    ; 4347
    ; 4348

; To disable and use a complete set of frames
; to have at least one frame per shot (curves editor)
episode=
     2784, ed=f
     2962, ed=f
     3114, ed=f
     3340, ed=f
     3449, ed=f
     3675, ed=f
     4065, ed=f
     4344, ed=f
     5068, ed=f
     5253, ed=f
     5265, ed=f
     6040, ed=f
     6120, ed=f
     6172, ed=f
     6440, ed=f
     6531, ed=f
     7946, ed=f
     8743, ed=f
    10502, ed=f
    11470, ed=f
    13619, ed=f
    14475, ed=f
    14830, ed=f
    14854, ed=f
    14965, ed=f
    15324, ed=f
    17273, ed=f
    17877, ed=f
    19767, ed=f
    19956, ed=f
    20215, ed=f
    20717, ed=f
    20940, ed=f
    22110, ed=f
    22332, ed=f
    22444, ed=f
    23558, ed=f
    24897, ed=f
    28600, ed=f
    28680, ed=f
    30055, ed=f
    30410, ed=f
    31500, ed=f
    32096, ed=f
    32492, ed=f



reportage=
    35100
    35200
    35262
    35285
    35310
    35420
    35565
    35643
    35732
    35830
    36000
    36030
    36070
    36150
    36330
    36379
    36410
    36450
    36470
    36554
    36570
    36745
    36822
    36890
    37193
    37197
    37327
    37412
    37580
    37637
    37737
    37970
    37984
    38020
    38083
    38115
    38167
    38228
    38314
    38378
    38439
    38485
    38560


asuivre=
    33910
    33934
    34069
    34239
    34305
    34385
    34419
    34527
