# study: filtering steps
; *extract
; deshake
; *temporal filtering
; *upscale
; denoise
; sharpen
; temporal filtering
; interpolate (50fps)
; interlace ?

; [filters_default]
; steps = """
;     *avisynth:  deinterlace;
;     *ffmpeg:    hqdn3d=2;
;     *esrgan:    model=2x_LD-Anime_Skr_v1.0;
;     *python:    unsharp_mask=2:0.5,
;                 bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.5;
;     *python:    bf_stabilizer;
;     *ffmpeg:    hqdn3d=3;
;     """




[filters_episode]
# 1.65 s/f
default="""
    *avisynth:   deinterlace;
    *python:     deshake;
    *ffmpeg:     hqdn3d=2;
    *esrgan:    model=sudo_RealESRGAN2x_Dropout_3.799.042_G;
    *python:     unsharp_mask=2:0.5,
                bilateralFilter=11:15:13,
                unsharp_mask=2:0.5;
    *python:     deshake;
    *ffmpeg:    hqdn3d=3;
    """

; [filters_episode]
; # 1.65 s/f
; default="""
;     *avisynth:   deinterlace;
;     *python:     deshake;
;     *ffmpeg:     hqdn3d=2;
;     *esrgan:    model=2x_LD-Anime_Skr_v1.0;
;     *python:     unsharp_mask=2:0.5,
;                 bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.5;
;     *python:     deshake;
;     *ffmpeg:    hqdn3d=3;
;     """


; default="""
;     *ffmpeg:  nnedi=weights=nnedi3_weights:nsize=s8x6:nns=n128:qual=slow:etype=s:pscrn=new3,fps=fps=25;
;     python:    deshake;
;     *ffmpeg:    hqdn3d=2;
;     *esrgan:    model=2x_LD-Anime_Skr_v1.0;
;     python:    unsharp_mask=2:0.5,
;                 bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.5;
;     python:    deshake;
;     *ffmpeg:    hqdn3d=3;
;     """


; default="""
;     *avisynth:  deinterlace;
;     python:    deshake;
;     *ffmpeg:    hqdn3d=2;
;     *esrgan:    model=2x_LD-Anime_Skr_v1.0;
;     python:    unsharp_mask=2:0.5,
;                 bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.5;
;     python:    deshake;
;     *ffmpeg:    hqdn3d=3;
;     """



; id_deinterlace=1
; deinterlace_ffmpeg="""
;     yadif=mode=1,
;     fps=fps=50
;     """


; id_deinterlace=2
; deinterlace_ffmpeg="""
;     yadif=mode=1,
;     fps=fps=50
;     """

; id_pre_upscale=28
; upscale="realcugan-ncnn-vulkan=s=2:n=1"


; id_upscale=28
; upscale="realcugan-ncnn-vulkan=s=2:n=1"

; id_denoise=28
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     unsharp_mask=3:0.9
;     """

; 86: warp affine
; id_sharpen=86
; sharpen="""
    ; """

; id_sharpen=31
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """



; [filters_episode]
; no SR-AI
; id_deinterlace=2
; deinterlace_ffmpeg="""
;     nnedi=weights=nnedi3_weights:
;     nsize=s8x6:
;     nns=n128:
;     qual=slow:
;     etype=s:
;     pscrn=none,
;     fps=fps=25
;     """


; id_upscale=3
; upscale="""
;     scale=width_upscale:height_upscale:lanczos4,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     """

; id_denoise=1
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     unsharp_mask=3:0.9
;     """

; id_sharpen=1
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """




; id_pre_upscale=19
; pre_upscale="""
;     fastNlMeansDenoisingColored=3:3:7:9,
;     edge_sharpen_sobel=3:0.2,
;     """


; id_upscale=24
; upscale="realesrgan=s=2:n=2x_LD-Anime_Skr"


; id_upscale=23
; upscale="realesrgan=s=2:n=realesr-general-x4v3"
# worst than 21

; id_upscale=22
; upscale="realesrgan=s=2:n=RealESRGAN_x4plus_anime_6B:t=256"
; bad on non vertical lines


# better than the others real esrgan

; id_upscale=20
; upscale="realesrgan=s=2:n=RealESRGAN_x2plus"


; id_upscale=19
; upscale="realcugan-ncnn-vulkan=s=2:n=1"

# upscale="realesrgan=s=2:n=RealESRGAN_x2plus" is better than lanczos
#   but bad compared to realcugan

; id_upscale=70
; ; upscale="realesrgan_ncnn=s=2:n=2x_LD-Anime_Skr_v1_fp32"
; upscale="realcugan-ncnn-vulkan=s=2:n=0"


; id_upscale=80
; upscale="realesrgan=s=2:n=2x_LD-Anime_Skr_v1"


; id_sharpen=87
; # unused, replaced by stabilization
; sharpen="""
;     unsharp_mask=3:0.3,
;     """



; id_upscale=16
; upscale="realcugan-ncnn-vulkan=s=2:n=1"

; id_denoise=16
; denoise="""
;     unsharp_mask=3:0.3,
;     """

; id_sharpen=16
; # unused, replaced by stabilization
; sharpen="""
;     unsharp_mask=3:0.3,
;     """


; id_upscale=21
; upscale="realesrgan=s=2:n=realesr-animevideov3"
; id_denoise=17
; denoise="""
;     unsharp_mask=3:0.3,
;     bilateralFilter=9:15:15,
;     unsharp_mask=3:0.2,
;     """
; 86: warp affine
; id_sharpen=86
; sharpen="""
;     """


; 85: homography
; id_sharpen=85
; sharpen="""
;     """

;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     edge_sharpen_sobel=3:0.15

; [filters_episode]
; id_pre_upscale=16
; pre_upscale="""
;     edge_sharpen_sobel=3:0.3,
;     """

; id_upscale=16
; upscale="realcugan-ncnn-vulkan=s=2:n=3"
; ; upscale="realcugan-ncnn-vulkan=g=-1:s=2:n=3"

; id_denoise=5
; denoise="""
;     """

; id_sharpen=5
; sharpen="""
;     """


; [filters_episode]
; id_upscale=33
; upscale_ffmpeg="""
;     scale=width_upscale:height_upscale:lanczos+accurate_rnd+bitexact
;     """


; id_denoise=33
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13
;     """

; ; sharpen qui devra être en commun avec l'édition k.
; id_sharpen=33
; sharpen="""
;     unsharp_mask=3:0.9,
;     bilateralFilter=11:15:15,
;     unsharp_mask=3:0.9,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:21:21,
;     edge_sharpen_sobel=3:0.2
;     """

; [filters_episode]
; id_upscale=25
; upscale_ffmpeg="""
;     scale=width_upscale:height_upscale:lanczos+accurate_rnd+bitexact,
;     fftdnoiz=10:1:64:0.5
;     """

; id_denoise=51
; denoise="""
;     fastNlMeansDenoisingColored=5:5:5:9,
;     unsharp_mask=3:0.9,
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     edge_sharpen_sobel=3:0.15
;     """



; sharpen qui devra être en commun avec l'édition k.
; incrémenter l'indice pour voir les différences des modifications du 'denoise filter'
; id_sharpen=12
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     edge_sharpen_sobel=3:0.15
;     """

[parts]
g_debut=0:2329
precedemment=0:0
episode=2329:33458
g_asuivre=33458:33878
asuivre=33878:34578
g_reportage=34579:34849
reportage=34850:38674
g_fin=38675:40620

[offsets]
episode=
    0:-343
asuivre=
    0:-338
    ; 5986
    ; 5643


[asuivre]
shots=
    33540,
    33576,
    33720,
    33893,
    33966,
    33996,
    34080,
    34172:34206

    ; 34172:34240


[episode]
; 2675
; 2832
shots=
    2329
    2832
    2909
    2967
    3063
    3250
    3293
    3338
    3478
    3588
    3779
    3966
    4006
    4131
    4229
    4457
    4539
    4706
    4777
    5001
    5060
    5464
    5565
    5643
    5726
    5791
    5981
    6161
    6316
    6409
    6620
    6666
    6854
    7015
    7093
    7248
    7302
    7441
    7499
    7571
    7691
    7872
    7968
    8052
    8195
    8428
    8543
    8686
    8745
    8865
    8900
    8959
    9012
    9031
    9077
    9156
    9275
    9365
    9449
    9540
    9690
    9840
    9984
    10152
    10332
    10620
    10690
    10754
    10814
    11078
    11270
    11342
    11402
    11511
    11629
    11734
    11847
    11931
    12012
    12074
    12127
    12188
    12247
    12343
    12375
    12409
    12594
    12628
    12711
    12806
    12852
    12894
    12940
    12979
    13001
    13023
    13056
    13108
    13179
    13309
    13451
    13505
    13559
    13638
    13732
    13852
    14023
    14172
    14285
    14332
    14404
    14493
    14551
    14587
    14635
    14999
    15048
    15203
    15284
    15403
    15475
    15547
    15664
    15699
    15738
    15784
    15820
    15890
    15984
    16098
    16169
    16311
    16395
    16562
    16722
    16724
    16726
    16728
    16729
    16730
    16731
    16733
    16734
    16762
    16767
    16770
    16772
    16773
    16774
    16775
    16776
    16777
    16780
    16781
    16798
    16799
    16800
    16801
    16803
    16804
    16807
    16809
    16811
    16813
    16814
    16815
    16816
    16817
    16819
    16820
    16821
    16822
    16831
    16895
    17023
    17118
    17170
    17389
    17417
    17441
    17465
    17537
    17584
    17740
    17851
    18029
    18316
    18475
    18605
    18661
    18781
    18913
    18985
    19165
    19202
    19471
    19626
    19782
    19854
    19925
    20021
    20133
    20253
    20434
    20504
    20575
    20695
    20778
    20990
    21134
    21235
    21295
    21337
    21431
    21539
    21600
    21697
    21715
    21781
    21889
    22009
    22171
    22381
    22676
    22872
    23063
    23131
    23198
    23274
    23432
    23552
    23684
    23823
    23888
    23960
    24019
    24050
    24122
    24170
    24338
    24415
    24734
    24807
    24866
    24909
    25220
    25340
    25779
    25865
    25961
    26033
    26237
    26321
    26477
    26548
    26692
    26817
    26877
    27069
    27129
    27321
    27440
    27580
    27755
    27851
    27952
    28024
    28049
    28110
    28154
    28270
    28326
    28396
    28443
    28474
    28642
    28701
    28894
    28966
    29026
    29137
    29218
    29287
    29336
    29480
    29624
    29780
    29974
    30097
    30242
    30384
    30716
    30823
    30991
    31097
    31217
    31289
    31409
    31586
    31657
    31783
    31901
    31961
    32044
    32080
    32100
    32119
    32158
    32277
    32405
    32517
    32601
    32757
    33009:33458
