# [audio.<lang>] sections:
# fadeout is in seconds
# silence is in seconds
# timestamps are in nb of frames
# fade algos: 'sin', 'cos', 'log'

[audio.fr]
source = k
precedemment = 0:0
episode = 2698:33808, fadeout=1.0:cos, silence=0.5
g_asuivre = 33811:33878
asuivre = 33878:34583, silence=0.5
g_documentaire =
    34597:34612
    34597:34850
documentaire = 34850:38674, fadeout=0.5:log, silence=0.5



[audio.en]
source = f
precedemment = 0:0
episode = 2660:33465, fadeout=1.5:cos, silence=0.5
g_asuivre = 33469:33540
asuivre = 33540:34243, silence=0.5
g_documentaire =
    34275:34289
    34275:34289
    34275:34514
# The end of the documentary is overlapped by end credits
documentaire = 34514:38124
            35495:35565, fadeout=2:cos, silence=0.5


[video]
source = f
documentaire = ed=f, fadeout=1.5
asuivre = fadeout=2.0


[shots_episode.fr]
000 = ed=k, ep=1, shot=0


[shots_documentaire.fr]
# 009 = ep=1, shot=9    37807
# 010 = ep=1, shot=10    37834 (1st half)
009 = shot=009, segments=37807:27
010 = ep=25, shot=001, segments=37727:117
011 = ep=25, shot=002
012 = ep=25, shot=003, segments=37922:75
013 = shot=011
014 = shot=012
