
[filters_episode]
id_upscale=25
upscale_ffmpeg="""
    scale=width_upscale:height_upscale:lanczos+accurate_rnd+bitexact,
    fftdnoiz=10:1:64:0.5
    """

# denoise is the filter used before merging the background and the foreground images
id_denoise=50
denoise="""
    fastNlMeansDenoisingColored=5:5:7:13,
    unsharp_mask=3:0.9,
    morphologyEx=MORPH_RECT:3:1,
    fastNlMeansDenoisingColored=3:3:5:7,
    unsharp_mask=2:1.2,
    morphologyEx=MORPH_RECT:3:1,
    bilateralFilter=11:15:13,
    edge_sharpen_sobel=3:0.15
    """


; sharpen qui devra être en commun avec l'édition k.
; incrémenter l'indice pour voir les différences des modifications du 'denoise filter'
id_sharpen=12
sharpen="""
    morphologyEx=MORPH_RECT:3:1,
    fastNlMeansDenoisingColored=3:3:5:7,
    unsharp_mask=2:1.2,
    morphologyEx=MORPH_RECT:3:1,
    bilateralFilter=11:15:13,
    edge_sharpen_sobel=3:0.15
    """

[parts]
g_debut=0:2650
precedemment=0:0
episode=2672:33808
g_asuivre=33809:33878
asuivre=33878:34578
g_reportage=34579:34849
reportage=34850:38674
g_fin=38675:40620

[frames]
offsets_episode=
    0:-343

    ; 5986
    ; 5643
