# [audio.<lang>] sections:
# fadeout is in seconds
# silence is in seconds
# timestamps are in nb of frames
# fade algos: 'sin', 'cos', 'log'

[audio.fr]
source = k
precedemment = 0:0
episode = 2698:33808, fadeout=1.0:cos, silence=0.5
g_asuivre = 33811:33878
asuivre = 33878:34583, silence=0.5
g_documentaire =
    34597:34612
    34597:34850
documentaire = 34850:38674, fadeout=0.5:log, silence=0.5



[audio.en]
source = f
precedemment = 0:0
episode = 2660:33465, fadeout=1.5:cos, silence=0.5
g_asuivre = 33469:33540
asuivre = 33540:34243, silence=0.5
g_documentaire =
    34275:34289
    34275:34289
    34275:34514
    34260:34275
# The end of the documentary is overlapped by end credits
documentaire = 34514:38124
            35495:35565, fadeout=2:cos, silence=0.5



[video.fr]
source = f
documentaire = ed=k, fadeout=1.0


[video.en]
source = f
documentaire = ed=f, fadeout=1.0


# Exemple of shot
; 000= ed=k, ep=1, shot=0, part=episode, segment=1240:1350
; warning: segment is not verified. do not use

[shots_episode.fr]
000 = ed=k, ep=1, shot=0

# This also works:
; [shots_episode]
; 000_fr = ed=k, ep=1, shot=0
