[audio.fr]
# Use the B edition (stereo)
source = b:ep01
g_fin = 38673:40575, avsync=0.5, silence=0.5, gain=3

# Mettre en commentaire les lignes ci-dessus et dé-commenter les suivantes
# si l'edition f n'est pas disponible. La source sera l'édition k (mono)
; source = k:ep01
; g_fin =
;     868:80.171, avsync=0.5
;     1591.822:1596.390, gain=0.5
;     80.171:2666, silence=0.8

[audio.en]
source = f:ep02
g_fin = 40128:41941, silence=0.5



[video.en]
; source = f:ep11
; use ep01 for debug
source = f:ep01
g_fin = fadeout=2.0


; [video.fr]
; source = s:ep11
; g_fin = fadeout=2.0

[video.fr]
source = j:ep99
g_fin = fadeout=2.0

[scenes_g_fin.fr]
max = 11
000 = ep=99, ed=j, scene=0
001 = ep=99, ed=j, scene=1
002 = ep=99, ed=j, scene=2
003 = ep=99, ed=j, scene=3
004 = ep=99, ed=j, scene=4
005 = ep=99, ed=j, scene=5
006 = ep=99, ed=j, scene=6
007 = ep=99, ed=j, scene=7


008 = ep=99, ed=j, scene=9
009 = ep=99, ed=j, scene=10
010 = ep=99, ed=j, scene=11
011 = ep=99, ed=j, scene=8

# English is not the same! shorter
; missing 39911 -> 40043 to put @39194

; color correction:
; f:    ep01_39193__f__
; k:    ep01_40044__s__
; resized: 749x577 (-18,1)

# scenes:
#   3: nlmeans + AnimeSR_v2 + BeaverIt
#   4: nlmeans + AnimeSR_v2 + BeaverIt
#   6: nlmeans + AnimeSR_v2 + BeaverIt
#   11: nlmeans + AnimeSR_v2 + BeaverIt


