[audio.fr]
# Use the B edition (stereo)
source = b:ep01
g_fin = 38675:40550, gain=3

# Mettre en commentaire les lignes ci-dessus et dé-commenter les suivantes
# si l'edition f n'est pas disponible. La source sera l'édition k (mono)
; source = k:ep01
; g_fin =
;     868:80.171, avsync=0.5
;     1591.822:1596.390, gain=0.5
;     80.171:2666, silence=0.8

[audio.en]
source = f:ep02
g_fin = 40128:41930


[video]
source = j:ep99
g_fin = fadein=1, fadeout=3


[scenes]
max = 11
000 = segment=3327:,
    effect=overlay:700:g_fin_01.png:35:125,
    effect=overlay:700:g_fin_02.png:170:100
001 = segment=:15
002 = segment=3655:435
004 = segment=:24
005 = segment=:22
006 = segment=4224:70
007 = segment=:40
008 = scene=9, segment=:55
009 = scene=10, segment=4693:285
010 = scene=11, segment=5002:295
011 = scene=8, segment=:285


[scenes.en]
009 = scene=10, segment=4853:125

# s_ep11
; 38882
; text: 38916   39042
; text: 39049   39150
