[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2698:3421
episode = 3434:33428
g_asuivre = 33555:33629
asuivre = 33629:34268
g_documentaire = 34277:34544
documentaire = 34545:38887


[shots_precedemment]
000 = 2698:3421
; 2767

[shots_episode]
000 = 3434:33428
; 3739

[shots_asuivre]
000 = 33629:34268
; 33710

[shots_documentaire]
000 = 34545:38887
