[audio.fr]
source = k
precedemment = 2670:3340
episode = 3340:35766, fadeout=0.25:log, silence=0.5
g_asuivre = 35766:35858
asuivre = 35858:36487, fadeout=2.0:cos, silence=0.5
g_documentaire =
    36501:36515
    36501:36747
documentaire = 36747:40075, fadeout=3.0:cos, silence=0.5

[audio.en]
source = f
precedemment = 2722:3433
episode = 3433:35793, fadeout=0.25:log, silence=0.5
g_asuivre = 35812:35884
asuivre = 35884:36532, fadeout=2.0:cos, silence=0.5
g_documentaire =
    36547:36561
    36547:36802
documentaire = 36802:40100, silence=0.5

[video]
# No differences between en/fr
source = f
episode = fadein=1.6
asuivre = fadeout=2.0
documentaire = ed=f, fadeout=2.0

; [shots_episode]
; 000=

