[audio.fr]
source = k
precedemment = 2670:3340
episode = 3340:35766, fadeout=0.25:log, silence=0.5
g_asuivre = 35766:35858
asuivre = 35858:36487, fadeout=2.0:cos, silence=0.5
g_reportage =
    36501:36515
    36501:36747
reportage = 36747:40075, fadeout=3.0:cos, silence=0.5

[audio.en]
source = f


[video]
# No differences between en/fr
source = f
episode = fadein=1.6
asuivre = fadeout=2.0
reportage = ed=f, fadeout=1.0

; [shots_episode]
; 000=

