


[filters_g_debut]

# Upscale with opencv
id_pre_upscale=10
pre_upscale_ffmpeg="""
    bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic
    """


id_upscale=10
upscale="""
    scale=width_upscale:height_upscale:bicubic
    """


id_denoise=10
denoise="""
    fastNlMeansDenoisingColored=5:5:7:13,
    unsharp_mask=3:1.2
    """


id_sharpen=10
sharpen="""
    morphologyEx=MORPH_RECT:3:1,
    fastNlMeansDenoisingColored=3:3:5:7,
    unsharp_mask=2:1.3,
    morphologyEx=MORPH_RECT:3:1,
    bilateralFilter=11:15:13
    """



[parts]
g_debut=0:2670



; [g_debut]
; shots=
;        0
;      648
;      798
;     1086
;     1297
;     1508
;     1632
;     1796
;     1877
;     1914
;     1955
;     2003
;     2198
;     2521:2630

[frames]
offsets_g_debut=0:2
offsets_g_reportage=0:2037
offsets_g_fin=0:1415


