
[audio.fr]
source = k
precedemment = 2661:3381
episode = 3381:33615, fadeout=0.50:cos, silence=0.5
g_asuivre = 33617:33689
asuivre = 33689:34336, fadeout=0.50:cos, silence=0.5
g_documentaire =
    34365:34379
    34365:34379
    34365:34604
documentaire = 34604:38906, fadeout=1.00:cos, silence=0.5


[audio.en]
source = f
# random values to be able to extract audio
precedemment = 2700:3400
episode = 3400:35000, silence=0.5
g_asuivre = 35000:35100
asuivre = 35100:35700, silence=0.5
g_documentaire =
    35700:36000
documentaire = 36000:39000, silence=0.5


[video]
source = f

; [video.fr]
; source = k
; precedemment  = 2662:3377
; episode = 3398:-1
; ; g_asuivre =
; asuivre = 33689:-1
; ; g_documentaire =
; documentaire = 34606:38905, fadeout=1.0


