[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2695:3403
episode = 3445:33237
g_asuivre = 33252:33327
asuivre = 33327:33960
g_documentaire = 33972:34240
documentaire = 34241:38540


[shots_precedemment]
000 = 2695:3403
; 2759

[shots_episode]
000 = 3445:33237
; 3697

[shots_asuivre]
000 = 33327:33960
; 33420

[shots_documentaire]
000 = 34241:38540

