[options]
; Add some tasks after deinterlace when it is the last task (--vfilter deinterlace)
; 'replace' is always enabled, except if defined in the 'discard_tasks' option
; possible tasks: rgb
; use comma between tasks
deinterlace_add_tasks = rgb

; Add some tasks after upscale when it is the last task (--vfilter upscale)
; 'replace' is always enabled, except if defined in the 'discard_tasks' option
; 'rgb' is always done if geometry is enabled
;
; WARNING: the image processing may use the pre_upscale filter it has been done by FFMPEG filter
;           in a previous generation. Possible way to avoid this is to use the --force command
upscale_add_tasks = geometry

; Discard some tasks (for debug purpose)
; possible tasks: stitching, pre_upscale, replace
; use comma between tasks;
;
; WARNING: pre_upscale and replace flag SHALL BE REMOVED:
;           - for the FULL generation
discard_tasks = stitching


[settings]
video_fps=25
video_pixel_format="yuv420p"
video_color_space="bt709"
video_color_range="tv"
video_quality="-c:v libx264 -preset medium -crf 17"
video_tune="-tune animation"
video_film_tune="-tune animation"
; video_film_tune="-tune film"
verbose="-hide_banner -loglevel warning"
frame_format="png"
audio_format="wav"


[dimensions]
width_initial=720
height_initial=576
width_upscale=1440
height_upscale=1152
width_final=1440
height_final=1080


[filters]
deinterlace_ffmpeg="""
    nnedi=weights=nnedi3_weights.bin:
    nsize=s8x6:
    nns=n128:
    qual=slow:
    etype=s:
    pscrn=new,
    fps=fps=25"""
id_deinterlace=1


[layers]
; used when stitching images
fgd=k
bgd=a