[dimensions]
width_initial=720
width_deinterlace=720

[filters]
# Replace 720 by width_upscale * SAR
id_deinterlace=2
deinterlace_ffmpeg="""
    nnedi=weights=nnedi3_weights.bin:
    nsize=s8x6:
    nns=n128:
    qual=slow:
    etype=s:
    pscrn=new,
    fps=fps=25,
    scale=720:576:lanczos+accurate_rnd+bitexact
    """

; Au revoir... A bientôt...