
[filters]
upscale_ffmpeg="""
    bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic,
    scale=width_upscale:height_upscale:sws_flags=lanczos+accurate_rnd+bitexact+full_chroma_int,
    setsar=1,setdar=1
    """
id_upscale=3


; Au revoir... A bientôt...