
; [filters]
; # Filtres par défaut pour cette édition, ils peuvent être remplacés
; # par ceux définies dans les épisodes/génériques
; ; id_upscale=0
; ; upscale_ffmpeg="""
; ;     bm3d=sigma=18:block=4:bstep=2:group=1:estim=basic,
; ;     scale=width_upscale:height_upscale:sws_flags=lanczos+accurate_rnd+bitexact+full_chroma_int,
; ;     setsar=1,setdar=1
; ;     """

; ; id_upscale=1
; ; upscale_ffmpeg="""
; ;     bm3d=sigma=18:block=4:bstep=2:group=1:estim=basic,
; ;     scale=width_upscale:height_upscale:sws_flags=lanczos+accurate_rnd+bitexact+full_chroma_int,
; ;     setsar=1,setdar=1
; ;     """

; id_denoise=0
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     unsharp_mask=3:0.9
;     """


; Au revoir... A bientôt...