[dimensions]
width_initial=352
width_deinterlace=720


; [filters]
; # Replace 720 by width_upscale * SAR
; id_deinterlace=2
; deinterlace_ffmpeg="""
;     nnedi=weights=nnedi3_weights:
;     nsize=s8x6:
;     nns=n128:
;     qual=slow:
;     etype=s:
;     pscrn=new,
;     fps=fps=25,
;     scale=width_deinterlace:height_deinterlace:lanczos
;     """

; Au revoir... A bientôt...