[directories]
; relative or absolute directories
; output directories shall exist, otherwise it will use the dfault ones

; where the inpute video shall be stored
inputs="inputs"

; cache is the directory where all generate images are stored during the processing.
;
cache="N:\cache"
cache_progressive="D:\mco\cache\progressive"

; frames directory is a directory to save frames extracted for study purpose
; 2023-07-29: unused
frames="frames"

; hashes directory contains a log of all hashes for each filter. Usefull for study.
hashes="hashes"

; outputs directory contains the output files
outputs="outputs"

; MKV Tool Nix installation path (default)
mkvmerge_win="C:\Program Files\MKVToolNix"

; 3rd parties directory, refer to installation doc
3rd_party="../mco_3rd_party"


; https://ffmpeg.org/download.html
; Linux
ffmpeg="ffmpeg-6.0-amd64-static"
; Windows
ffmpeg_win="ffmpeg-6.0-essentials_build\bin"


; https://github.com/bilibili/ailab/tree/main/Real-CUGAN
real_cugan = "ailab/Real-CUGAN"

; https://github.com/xinntao/Real-ESRGAN
real_esrgan = "Real-ESRGAN"

; https://github.com/JoeyBallentine/ESRGAN
esrgan = "ESRGAN"
pytorch = "pytorch"

; https://github.com/TencentARC/AnimeSR
animesr = "AnimeSR"

; https://github.com/cszn/SCUNet


; https://github.com/dubhater/vapoursynth-nnedi3/tree/master/src
; just for testing purpose, unused since avisynth deinterlace script is used
nnedi3_weights="nnedi3_weights.bin"



; default directories, do not modify this
cache_default="cache"
frames_default="frames"
cache_progressive_default="cache/progressive"
