
[audio.fr]
source = k
precedemment = 2669:3745
episode = 3745:33980, fadeout=0.50:cos, silence=0.5
g_asuivre = 33980:34053
asuivre = 34053:34684, fadeout=0.50:cos, silence=0.5
g_documentaire =
    34685:34953
documentaire = 34953:38865, fadeout=0.50:cos, silence=0.5


[audio.en]
source = f
# random values just to extract audio track
precedemment = 2695:3773
episode = 3773:34019, fadeout=0.25:cos, silence=0.5
g_asuivre = 34019:34089
asuivre = 34089:34738, fadeout=0.50:cos, silence=0.5
g_documentaire =
    34767:34781
    34767:34781
    34767:35008
documentaire = 35008:38914, fadeout=0.75:cos, silence=0.5


[video]
source = f


; [video.fr]
; source = k
; precedemment  = 2670:3738
; episode = 3747:-1
; ; g_asuivre =
; asuivre = 34053:-1
; ;g_documentaire =
; documentaire = 34953:38860, fadeout=1.0

