[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2683:3402
episode = 3414:33464
g_asuivre = 33516:33591
asuivre = 33591:34234
g_documentaire = 34241:34507
documentaire = 34508:38897


[shots_precedemment]
000 = 2683:3402
; 2739

[shots_episode]
000 = 3414:33464
; 3607

[shots_asuivre]
000 = 33591:34234
; 33641

[shots_documentaire]
000 = 34508:38897
