# [audio.<lang>] sections:
# fadeout is in seconds
# silence is in seconds
# timestamps are in nb of frames
# fade algos: 'sin', 'cos', 'log'

[audio.fr]
source = k
precedemment = 0:0
episode = 2698:33808, fadeout=1.0:cos, silence=0.5
g_asuivre = 33811:33878
asuivre = 33878:34583, silence=0.5
g_documentaire =
    34597:34612
    34597:34850
documentaire = 34850:38674, fadeout=0.5:log, silence=0.5



[audio.en]
source = f
precedemment = 0:0
episode = 2660:33465, fadeout=1.5:cos, silence=0.5
g_asuivre = 33469:33540
asuivre = 33540:34243, silence=0.5
g_documentaire =
    34275:34289
    34275:34289
    34275:34514
# The end of the documentaire is overlapped by end credits
documentaire = 34514:38124
            35495:35565, fadeout=2:cos, silence=0.5


[video]
source = f
documentaire = ed=f, fadeout=1.5
asuivre = fadeout=2.0


[scenes_documentaire.fr]
# 009 = ep=1, scene=9    37807
# 010 = ep=1, scene=10    37834 (1st half)
009 = scene=009, segments=37807:27
010 = ep=25, scene=001, segments=37727:117
011 = ep=25, scene=002
012 = ep=25, scene=003, segments=37922:75
013 = scene=011
014 = scene=012


[scenes_episode.fr]
# With edition f
000 = ed=k, ep=1, scene=0

# With edition j
001 = ed=j
002 = ed=j
003 = ed=j
004 = ed=j
005 = ed=j
006 = ed=j
007 = ed=f
008 = ed=j
009 = ed=f
010 = ed=j, scene=11
011 = ed=j, scene=12
012 = ed=j, scene=13
013 = ed=j, scene=14
; 14 can be replaced only if 14 and 18 have the same color grading
014 = ed=j, scene=15
015 = ed=j, scene=16
016 = ed=j, scene=17
017 = ed=j, scene=27, segments=6914:71

018 = ed=f
019 = ed=j, scene=18
020 = ed=f
021 = ed=f
022 = ed=f
; 23: j:21 possible but duplicate frames is required (add the latest 8 frames 75 -> 83)
023 = ed=f

; 24: j:22 possible only if color grading with f:20
024 = ed=j, scene=22

; 25: possible by adding a segment
; 025 = ed=j, scene=24 <- not possible because missing first frames
025 = ed=f
# 26 only if j:25 has been consolidated
026 = ed=j, scene=25

027 = ed=j, scene=26

; Does not exist, warning: color grading with scene 26  (20, 24, 26 must have the same color grading)
028 = ed=f

; scene j:28 is too short
029 = ed=f

; j is too short
030 = ed=f

; j: missing 1 frame in 31 but has one more in 32
031 = ed=j
032 = ed=j
033 = ed=j
034 = ed=j
035 = ed=j
036 = ed=j
037 = ed=j
038 = ed=j
039 = ed=j
040 = ed=j
041 = ed=j
042 = ed=j
043 = ed=j
044 = ed=j
045 = ed=j
046 = ed=j
047 = ed=j
048 = ed=j
049 = ed=j
050 = ed=j
051 = ed=j
052 = ed=j
053 = ed=j
054 = ed=j
055 = ed=j
056 = ed=j
057 = ed=j
058 = ed=j
059 = ed=j
060 = ed=j
061 = ed=j
062 = ed=j
063 = ed=j
064 = ed=j
065 = ed=j
066 = ed=j
067 = ed=j
068 = ed=j
069 = ed=j
070 = ed=j
071 = ed=j
072 = ed=j
073 = ed=j
074 = ed=j
075 = ed=j
076 = ed=j
077 = ed=j
078 = ed=j
079 = ed=j
080 = ed=j
081 = ed=j
082 = ed=j
083 = ed=j
084 = ed=j
085 = ed=j
086 = ed=j
087 = ed=j
088 = ed=j
089 = ed=j
090 = ed=j
091 = ed=j
092 = ed=j
093 = ed=j
094 = ed=j
095 = ed=j
096 = ed=j
097 = ed=j
098 = ed=j
099 = ed=j
100 = ed=j
101 = ed=j
102 = ed=j
103 = ed=j
104 = ed=j
105 = ed=j
106 = ed=j
107 = ed=j
108 = ed=j
109 = ed=j
110 = ed=j
111 = ed=j
112 = ed=j
113 = ed=j
114 = ed=j
115 = ed=j
116 = ed=j
117 = ed=j
118 = ed=j
119 = ed=j
120 = ed=j
121 = ed=j
122 = ed=j
123 = ed=j
124 = ed=j
125 = ed=j
126 = ed=j
127 = ed=j
128 = ed=j
129 = ed=j
130 = ed=j
131 = ed=j
132 = ed=j
133 = ed=j
134 = ed=j
135 = ed=j
136 = ed=j
137 = ed=j
138 = ed=j
139 = ed=j
140 = ed=j
141 = ed=j
142 = ed=j
143 = ed=j
144 = ed=j
145 = ed=j
146 = ed=j
147 = ed=j
148 = ed=j
149 = ed=j
150 = ed=j
151 = ed=j
152 = ed=j
153 = ed=j
154 = ed=j
155 = ed=j
156 = ed=j
157 = ed=j
158 = ed=j
159 = ed=j
160 = ed=j
161 = ed=j
162 = ed=j
163 = ed=j
164 = ed=j
165 = ed=j
166 = ed=j
167 = ed=j
168 = ed=j
169 = ed=j
170 = ed=j
171 = ed=j
172 = ed=j
173 = ed=j
174 = ed=j
175 = ed=j
176 = ed=j
177 = ed=j
178 = ed=j
179 = ed=j
180 = ed=f
181 = ed=f
182 = ed=j
183 = ed=j
184 = ed=j
185 = ed=j
186 = ed=j
187 = ed=j
188 = ed=j
189 = ed=j
190 = ed=j
191 = ed=j
192 = ed=j
193 = ed=j
194 = ed=j
195 = ed=j
196 = ed=j
197 = ed=j
198 = ed=j
199 = ed=j
200 = ed=j
201 = ed=j
202 = ed=j
203 = ed=j
204 = ed=j
205 = ed=j
206 = ed=j
207 = ed=j
208 = ed=j
209 = ed=j
210 = ed=j
211 = ed=j
212 = ed=j
213 = ed=j
214 = ed=j
215 = ed=j
216 = ed=j
217 = ed=j
218 = ed=j
219 = ed=j
220 = ed=j
221 = ed=j
222 = ed=j
223 = ed=j
224 = ed=j
225 = ed=j
226 = ed=j
227 = ed=j, scene=230
228 = ed=j, scene=231
229 = ed=j, scene=233
230 = ed=j, scene=228
231 = ed=j, scene=229
232 = ed=j, scene=234
233 = ed=j, scene=235
234 = ed=j, scene=236
235 = ed=j, scene=237
236 = ed=j, scene=238
237 = ed=j, scene=239

; f: 238 (168) = 240 (78) + 242 (88) -> (166)
238 = ed=j, scene=240
239 = ed=j, scene=242

240 = ed=j, scene=243
241 = ed=j, scene=244
242 = ed=j, scene=245
243 = ed=j, scene=246
244 = ed=j, scene=247
245 = ed=j, scene=250
246 = ed=j, scene=251
247 = ed=j, scene=252
248 = ed=j, scene=253
249 = ed=j, scene=254
250 = ed=j, scene=255
251 = ed=j, scene=256
252 = ed=j, scene=257
253 = ed=j, scene=258
254 = ed=j, scene=259
255 = ed=j, scene=260
256 = ed=j, scene=261
257 = ed=j, scene=262
258 = ed=j, scene=263
259 = ed=j, scene=264
260 = ed=j, scene=265
261 = ed=j, scene=266
262 = ed=j, scene=267
263 = ed=j, scene=268
264 = ed=j, scene=269
265 = ed=j, scene=270
266 = ed=j, scene=271
267 = ed=j, scene=272
268 = ed=j, scene=273
269 = ed=j, scene=274
270 = ed=f, scene=271
271 = ed=f, scene=272
272 = ed=f, scene=273
273 = ed=f, scene=274
274 = ed=f, scene=275
275 = ed=f, scene=276


