[audio]
# temp version just for comparison of g_reportage
source = k
precedemment = 2658:3388
episode = 3388:33602, silence=0.5
g_asuivre = 33610:33684
asuivre = 33684:34344, silence=0.5
g_reportage =
    34359:34373
    34359:34373
    34359:34598
reportage = 34598:38844, fadeout=0.3:, silence=0.5


[video]
# temp version just for comparison of g_reportage
precedemment = 2658:3373
episode = 3383:-1
; g_asuivre =
asuivre = 33684:-1
; g_reportage =
reportage = 34597:38846, fadeout=1.0
