[deinterlace]
ffv1=yes
range=33600:33700


[filters_g_asuivre]
default="""
    avisynth:   deinterlace;
    *esrgan:    model=2x_LD-Anime_Skr_v1.0;
    *esrgan:    model=1x_BeaverIt;
    *python:    bilateralFilter=11:15:13,
                unsharp_mask=2:0.5;
    """



; [filters_g_asuivre]
; id_upscale=1
; upscale="realcugan-ncnn-vulkan=s=2:n=0"
; ; upscale="realcugan-ncnn-vulkan=g=-1:s=2:n=0"

; id_denoise=1
; denoise="""
;     """

; id_sharpen=1
; sharpen="""
;     """



# non AI upscaling
; [filters_g_asuivre]
; note: ffmpeg fftdnoiz enlève la 2e narine
; id_upscale=1
; upscale="""
;     scale=width_upscale:height_upscale:lanczos4
;     """

; id_denoise=1
; denoise="""
;     unsharp_mask=3:0.5,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     """

; id_sharpen=1
; sharpen="""
;     bilateralFilter=13:25:25,
;     unsharp_mask=3:0.3,
;     gaussianBlur=3:1.1,
;     bilateralFilter=15:25:25,
;     edge_sharpen_sobel=3:0.15,
;     unsharp_mask=3:0.1,
;     """




; id_sharpen=50
; sharpen="""
;     bilateralFilter=13:25:25,
;     unsharp_mask=3:0.3,
;     gaussianBlur=3:1.1,
;     bilateralFilter=15:25:25,
;     unsharp_mask=3:0.3,
;     edge_sharpen_sobel=3:0.15
;     """


; id_sharpen=40
; sharpen="""
;     bilateralFilter=13:25:25,
;     unsharp_mask=3:0.3,
;     gaussianBlur=3:1.1,
;     bilateralFilter=15:25:25,
;     unsharp_mask=3:0.3,
;     """




; id_sharpen=43
; sharpen="""
;     unsharp_mask=3:0.5,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=15:35:35,
;     unsharp_mask=3:0.2,
;     bilateralFilter=15:25:25,
;     unsharp_mask=3:0.3,
;     """


; [filters_g_asuivre]
; id_pre_upscale=44
; pre_upscale_ffmpeg="""
;     """

; id_upscale=44
; upscale="""
;     scale=width_upscale:height_upscale:lanczos
;     """

; id_denoise=44
; denoise="""
;     """

; id_sharpen=44
; sharpen="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=15:35:35,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=3:0.8,
;     bilateralFilter=11:15:13
;     """


; id_sharpen=45
; sharpen="""
;     unsharp_mask=3:0.5,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     gaussianBlur=3:1.5,
;     unsharp_mask=3:0.2,
;     bilateralFilter=15:35:35,
;     unsharp_mask=3:0.3,
;     bilateralFilter=9:11:11,
;     unsharp_mask=3:0.3,
;     """

; id_sharpen=45
; sharpen="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     gaussianBlur=3:2,
;     unsharp_mask=2:0.3,
;     bilateralFilter=15:35:35,
;     unsharp_mask=3:0.3,
;     bilateralFilter=9:11:11,
;     unsharp_mask=3:0.3,
;     """




; id_denoise=47
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     gaussianBlur=3:3,
;     unsharp_mask=2:0.3,
;     bilateralFilter=15:35:35,
;     """

; id_sharpen=47
; sharpen="""
;     unsharp_mask=3:0.6,
;     bilateralFilter=9:11:11
;     """


; id_denoise=48
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     gaussianBlur=3:3,
;     bilateralFilter=15:35:35,
;     """

; id_sharpen=48
; sharpen="""
;     unsharp_mask=3:0.6,
;     bilateralFilter=9:11:11
;     """


; id_denoise=49
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     gaussianBlur=5:3,
;     bilateralFilter=15:35:35,
;     """

; id_sharpen=49
; sharpen="""
;     unsharp_mask=3:0.6,
;     bilateralFilter=9:11:11
;     """




; id_denoise=50
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=15:35:35,
;     """
; id_sharpen=50
; sharpen="""
;     unsharp_mask=3:0.6,
;     bilateralFilter=9:11:11
;     """




; id_denoise=52
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=20:51:51,
;     """
; id_sharpen=52
; sharpen="""
;     unsharp_mask=3:0.6,
;     bilateralFilter=9:11:11
;     """



; 2022-11-27
; [filters_g_asuivre]
; id_pre_upscale=15
; pre_upscale_ffmpeg="""
;     bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic
;     """

; id_upscale=15
; upscale="""
;     scale=width_upscale:height_upscale:lanczos
;     """


; id_denoise=15
; denoise="""
;     unsharp_mask=3:0.5,
;     fastNlMeansDenoisingColored=5:5:7:13
;     """

; id_sharpen=15
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.2,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """



[parts]
g_debut=0:2658
precedemment=2658:3373
episode=3383:33602
g_asuivre=33610:33684
asuivre=33684:34328
g_reportage=34331:34597
reportage=34597:38846
g_fin=38846:40825

[g_asuivre]
shots=
    33659:33660

[offsets]
g_debut=0:0
g_reportage=0:-139
g_fin=0:170
g_asuivre=0:0

