[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2698:3411
episode = 3442:33540
g_asuivre = 33657:33730
asuivre = 33732:34363
g_documentaire = 34380:34646
documentaire = 34647:38916


[shots_precedemment]
000 = 698:3411
; 2772

[shots_episode]
000 = 3442:33540
; 3717

[shots_asuivre]
000 = 33732:34363
; 33826

[shots_documentaire]
000 = 34647:38916
