[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2704:3419
episode = 3444:33647
g_asuivre = 33662:33736
asuivre = 33736:34360
g_documentaire = 34377:34645
documentaire = 34647:38963


[shots_precedemment]
000 = 2704:3419
; 2787

[shots_episode]
000 = 3444:33647
; 3678

[shots_asuivre]
000 = 33736:34360
; 33836

[shots_documentaire]
000 =34647:38963
