[audio]
source = k
precedemment = 2666:3379
episode = 3379:33571, silence=0.5
g_asuivre = 33590:33665
asuivre = 33665:34311, silence=0.5
g_reportage =
    34326:34340
    34326:34567
reportage = 34567:38873, fadeout=1.0:cos, silence=0.5


[video]
source = k
precedemment = 2668:3373
episode = 3392:-1
; g_asuivre =
asuivre = 33665:-1
; g_reportage =
reportage = 34577:38877, fadeout=1.0


[filters_episode]
id_sharpen=3
sharpen="""
    morphologyEx=MORPH_RECT:3:1,
    fastNlMeansDenoisingColored=3:3:5:7,
    unsharp_mask=2:1.2,
    morphologyEx=MORPH_RECT:3:1,
    bilateralFilter=11:15:13,
    brightness_contrast=255:130
    """

