
[filters_g_fin]
; note: ffmpeg fftdnoiz pas suffisemment probant et crée des artefacts
id_upscale=1
upscale="""
    scale=width_upscale:height_upscale:lanczos4
    """

id_denoise=1
denoise="""
    unsharp_mask=3:0.3,
    fastNlMeansDenoisingColored=5:5:7:13,
    bilateralFilter=20:51:51,
    """

id_sharpen=1
sharpen="""
    unsharp_mask=3:0.3,
    bilateralFilter=10:31:31,
    edge_sharpen_sobel=3:0.15,
    unsharp_mask=3:0.1,
    """



; [filters_g_fin]
; # Upscale with opencv
; id_pre_upscale=11
; pre_upscale="""
;     """
; ; bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic"""

; id_upscale=11
; upscale="""
;     scale=width_upscale:height_upscale:bicubic
;     """


; id_denoise=10
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=20:51:51,
;     """


; id_sharpen=10
; sharpen="""
;     unsharp_mask=3:0.3,
;     bilateralFilter=10:31:31
;     """



; morphologyEx=MORPH_RECT:3:1,
; fastNlMeansDenoisingColored=3:3:5:7,
; unsharp_mask=2:1,
; morphologyEx=MORPH_RECT:3:1,
; bilateralFilter=11:15:13,
; unsharp_mask=2:1.3,
; morphologyEx=MORPH_RECT:3:1,
; bilateralFilter=20:51:51
; """


; [filters_g_fin]
; # Upscale with opencv
; id_pre_upscale=2
; pre_upscale_ffmpeg="""
;     """
; ; bm3d=sigma=14:block=4:bstep=2:group=1:estim=basic"""

; id_upscale=2
; upscale="""
;     scale=width_upscale:height_upscale:bicubic
;     """


; id_denoise=9
; denoise="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=20:51:51,
;     """

; ; id_denoise=10
; ; denoise="""
; ;     unsharp_mask=3:0.3,
; ;     fastNlMeansDenoisingColored=7:7:13:17,
; ;     bilateralFilter=20:51:51,
; ;     """

; id_sharpen=9
; ; id_sharpen=5
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:1,
;     morphologyEx=MORPH_RECT:3:1
;     """



# 2021-09-01 15:47
; id_ffmpeg=0
; deinterlace_ffmpeg="""
;     nnedi=weights=nnedi3_weights.bin:
;     nsize=s8x6:
;     nns=n128:
;     qual=slow:
;     etype=s:
;     pscrn=new,
;     fps=fps=25"""
; upscale_ffmpeg="""
;     bm3d=sigma=25:block=4:bstep=2:group=1:estim=basic"""

; id_sharpen=48
; sharpen="""
;     unsharp_mask=3:0.3,
;     fastNlMeansDenoisingColored=5:5:7:17,
;     unsharp_mask=3:1.0,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:0.7,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13,
;     unsharp_mask=2:1.1,
;     morphologyEx=MORPH_RECT:3:1
;     """



[parts]
g_debut=0:2628
precedemment=2668:3373
episode=3392:33571
g_asuivre=33591:33665
asuivre=33665:34298
g_reportage=34312:34577
reportage=34577:38877
g_fin=38882:40854


[offsets]
g_debut=0:0
g_reportage=0:-156
g_fin=0:0



[g_fin]
shots=
    38882
    39173
    39194
    39648
    39696
    39720
    39742
    39818
    39857
    39913
    40208
    40512
    40812


