
[filters_episode]
id_sharpen=3
sharpen="""
    morphologyEx=MORPH_RECT:3:1,
    fastNlMeansDenoisingColored=3:3:5:7,
    unsharp_mask=2:1.2,
    morphologyEx=MORPH_RECT:3:1,
    bilateralFilter=11:15:13,
    brightness_contrast=255:130
    """




; [video]
; reference=s
; precedemment=2668:3374
; episode=3391:33573
; g_asuivre=33591:33665
; asuivre=33665:34301
; g_reportage=34312:34578
; reportage=34578:38877


