[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2703:3417
episode = 3443:33421
g_asuivre = 33488:33562
asuivre = 33562:34200
g_documentaire = 34208:34475
documentaire = 34492:38890


[shots_precedemment]
000 = 2703:3417
; 2770

[shots_episode]
000 = 3443:33421
; 3640

[shots_asuivre]
000 = 33562:34200
; 33585

[shots_documentaire]
000 = 34492:38890
