[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2705:3416
episode = 3441:33481
g_documentaire = 33500:33766
documentaire = 33767:38180


[shots_precedemment]
000 = 2705:3416
; 2748

[shots_episode]
000 = 3441:33481
; 3765

[shots_documentaire]
000 = 33767:38180
