
[audio.fr]
source = k
precedemment = 2659:3394
episode = 3394:33444, fadeout=1.00:cos, silence=0.5
g_asuivre = 0:0
asuivre = 0:0, silence=0
g_documentaire =
    33472:33486
    33472:33486
    33472:33715
documentaire = 33715:38124, silence=0.5


[audio.en]
source = f
precedemment = 2705:3443
episode = 3443:33498, fadeout=2.0:cos, silence=0.5
g_asuivre = 0:0
asuivre = 0:0, silence=0
g_documentaire =
    33526:33540
    33526:33540
    33526:33777
documentaire = 33777:38184, fadeout=0.25:cos, silence=0.5


[video]
source = f

; [video.fr]
; source = k
; precedemment  = 2660:3366
; episode = 3394:-1
; ; g_asuivre =
; asuivre = 0:-1
; ; g_documentaire =
; documentaire = 33712:38123, fadeout=1.0

