# -*- coding: utf-8 -*-
import sys

import collections
import configparser
import os
import os.path
import numpy as np
from pathlib import (
    Path,
    PosixPath,
)
from pprint import pprint

from filters.curve import Curve
from utils.common import (
    K_GENERIQUES,
    get_or_create_src_shot,
    nested_dict_set,
)

from parsers.parser_generiques import (
    get_dependencies_for_generique,
)

# n'utilise pas le no. de plan car en cas de modification de la
# liste des plans (ajout ou suppression), il pourrait y avoir des décalages
# le no. de plan est retrouvable par les parsers depuis le no. de trame
# et plus rapide encore lorsque la partie est spécifiée; lors de l'écriture automatique
# par l'éditeur, le no. de trame correspond à la 1ere trame du plan
#
# frame_no,<curve>


def parse_curve_configurations(db, k_ep_or_g:str):
    """ Parse configuration file
    It stores the curves selection info in each shot structure
    The config file is generated by the editors (video, curves)
    """

    # Open configuration file
    filepath = os.path.join(db['common']['directories']['config'], k_ep_or_g, "%s_curves.ini" % (k_ep_or_g))
    if filepath.startswith("~/"):
        filepath = os.path.join(PosixPath(Path.home()), filepath[2:])
    if not os.path.exists(filepath):
        # print("warning: %s:__parse_curve_configurations: %s, %s is missing" % (__name__, k_ep_or_g, filepath))
        return

    # Parse the file
    config = configparser.ConfigParser()
    config.read(filepath)
    for k_section in config.sections():
        # print("\tsection:%s" % (k_section))
        if '.' not in k_section:
            sys.exit("__parse_curve_configurations: error, no edition,ep,part specified")
        k_ed, k_ep, k_part = k_section.split('.')

        for frame_no_str in config.options(k_section):
            frame_no = int(frame_no_str)
            value_str = config.get(k_section, frame_no_str)
            k_curve = value_str.strip()
            if k_curve == '':
                continue

            # Get shot from frame no.
            # print("parse_curve_configurations, find %d in %s:%s:%s" % (frame_no, k_ed, k_ep, k_part))
            # shot = get_shot_from_frame_no_new(db, frame_no, k_ed=k_ed, k_ep=k_ep, k_part=k_part)
            #   replaced by a function which creates the src shot if not defined in the config file
            try:
                shot = get_or_create_src_shot(db, frame_no, k_ed=k_ed, k_ep=k_ep, k_part=k_part)
                if shot is None:
                    continue
            except:
                continue

            # Append curves struct to the shot
            shot['curves'] = {
                'k_curves': k_curve,
                'lut':None,
            }
            # print("\t=> %s:%s:%s: shot no. %s -> %s" % (k_ed, k_ep, k_part, shot['no'], shot['curves']['k_curves']))


def get_curves_channels_from_db(db, k_ed, k_ep, k_part, k_curves:str) -> dict:
    # Return also the curves as a single line
    curves_points_str = ""
    k_ep_or_g = k_part if k_part in K_GENERIQUES else k_ep

    # Open configuration file
    filepath = os.path.join(db['common']['directories']['config'], k_ep_or_g, "%s_curves_db.ini" % (k_ep_or_g))
    if filepath.startswith("~/"):
        filepath = os.path.join(PosixPath(Path.home()), filepath[2:])
    if not os.path.exists(filepath):
        # print("warning: %s:parse_curves_database: %s, %s is missing" % (__name__, k_ep_or_g, filepath))
        return None

    config = configparser.ConfigParser()
    config.read(filepath)

    if k_part in K_GENERIQUES:
        k_section = "%s.%s.%s" % (k_ed, k_ep, k_curves)
    else:
        k_section = "%s.%s" % (k_ed, k_curves)

    try:
        rgb_channels = {
            'r': Curve(),
            'g': Curve(),
            'b': Curve(),
            'm': Curve(),
        }
        for k_channel in ['r', 'g', 'b', 'm']:
            points_str = config.get(k_section, k_channel).replace(' ', '').strip()
            curves_points_str += "%s=%s;" % (k_channel, points_str)
            points = points_str.split(',')
            rgb_channels[k_channel].remove_all_points()
            for point in points:
                xy = point.split(':')
                rgb_channels[k_channel].add_point(np.float32(xy[0]),np.float32(xy[1]))
    except:
        print("Warning: %s:%s:%s: [%s] is not found in curves db: %s" % (k_ed, k_ep, k_part, k_section, filepath))
        return None
    return rgb_channels, curves_points_str[:-1]



def get_initial_curves_selection(db, k_ep, k_part) -> dict:
    # Create a dictionary of curves selection for each shot
    # It uses the shot_src so that this will work when replacing shots
    # from another episode/part
    # print("%s.get_curves_selection: src=%s:%s" % (__name__, k_ep, k_part))
    shot_curves = dict()

    # Get the list of editions and episode that are used by this ep/part
    if k_part in K_GENERIQUES:
        db_video = db[k_part]['video']
        dependencies = get_dependencies_for_generique(db, k_part_g=k_part)
        for k_ed_src in dependencies.keys():
            for k_ep_src in dependencies[k_ed_src]:

                # print("get_initial_curves_selection: get db_video for %s:%s:%s" % (k_ed_src, k_ep_src, k_part))
                if k_ep_src == '':
                    continue

                db_video = db[k_ep_src]['video'][k_ed_src][k_part]
                if 'shots' not in db_video.keys():
                    continue

                for shot in db_video['shots']:
                    shot_src = shot
                    shot_start = shot['start']

                    # Append to the dict if RGB curves are defined
                    if 'curves' not in shot.keys():
                        continue

                    if shot['curves'] is not None:
                        nested_dict_set(shot_curves, shot_src['curves'],
                            k_ed_src, k_ep_src, k_part, shot_start)


    else:
        for k_ed_src in db['editions']['available']:
            # print("get_initial_curves_selection: get db_video for %s:%s:%s" % (k_ed_src, k_ep, k_part))
            if k_ep == '':
                continue

            db_video = db[k_ep]['video'][k_ed_src][k_part]
            if 'shots' not in db_video.keys():
                continue

            for shot in db_video['shots']:
                shot_src = shot
                shot_start = shot['start']

                # Append to the dict if RGB curves are defined
                if 'curves' not in shot.keys():
                    continue

                if shot['curves'] is not None:
                    nested_dict_set(shot_curves, shot_src['curves'],
                        k_ed_src, k_ep, k_part, shot_start)

    # print("get_curves_selection")
    # pprint(shot_curves)
    return shot_curves



def parse_curves_database(db, k_ep_or_g:str, k_ed:str=''):
    db_curves = dict()

    # Open configuration file
    filepath = os.path.join(db['common']['directories']['config'], k_ep_or_g, "%s_curves_db.ini" % (k_ep_or_g))
    if filepath.startswith("~/"):
        filepath = os.path.join(PosixPath(Path.home()), filepath[2:])
    if not os.path.exists(filepath):
        # print("warning: %s:parse_curves_database: %s, %s is missing" % (__name__, k_ep_or_g, filepath))
        return db_curves

    # Parse the file
    config_curves_db = configparser.ConfigParser()
    config_curves_db.read(filepath)
    for k_section in config_curves_db.sections():
        if k_ep_or_g in K_GENERIQUES:
            k_ed_db, k_ep_db, k_curves = k_section.split('.')
        else:
            k_ed_db, k_curves = k_section.split('.')
            k_ep_db = k_ep_or_g

        if k_ed != '' and k_ed_db != k_ed:
            continue

        nested_dict_set(db_curves, {
            'k_curves': k_curves,
            'channels': {
                'r': Curve(),
                'g': Curve(),
                'b': Curve(),
                'm': Curve(),
            },
            'lut': None,
            'shots': list()
        }, k_ed_db, k_ep_db, k_curves)

        curves = db_curves[k_ed_db][k_ep_db][k_curves]
        for k_channel in ['r', 'g', 'b', 'm']:
            points_str = config_curves_db.get(k_section, k_channel).replace(' ', '').strip()
            points = points_str.split(',')
            curves['channels'][k_channel].remove_all_points()
            for point in points:
                xy = point.split(':')
                curves['channels'][k_channel].add_point(
                    np.float32(xy[0]),np.float32(xy[1]))

    # print("parse_curves_database")
    # pprint(db_curves)
    # sys.exit()
    return db_curves







def save_curves_database(db, k_ep_or_g:str, k_ed:str=''):
    print("TODO: save_curves_database")

    # for k in ['m', 'r', 'g', 'b']:
    #     value_str = "%s=" % (k)
    #     for p in channels[k].points():
    #         value_str += "%.06f:%.06f;" % (p.x(), p.y())
    #     value_str = value_str[:-1]
    #     curve_file.write(value_str + '\n')
    # curve_file.close()

