[editions]
discard = a, s0


[settings]
video_color_space = "bt709"
video_color_range = "tv"
audio_format = "wav"
fps = 25

; language = 'en'


[dimensions]
width_final = 1440
height_final = 1080


[video_settings_lr]
codec = h264
# codec_options = "-preset placebo -crf 15"
pix_fmt = yuv420p


[video_settings_upscale]
codec = h264
codec_options = "-preset slow -crf 15"
pix_fmt = yuv420p

[video_settings_hr]
codec = dnxhd
codec_options = "-profile:v dnxhr_hqx"
pix_fmt = yuv422p10le
pad = 24

[video_settings_final]
codec = h264
codec_options = "-preset slow -crf 15"
pix_fmt = yuv420p

