[editions]
discard = a, s0


[settings]
video_pixel_format = "yuv420p"
video_color_space = "bt709"
video_color_range = "tv"
video_quality = "-c:v libx264 -preset slow -crf 17"
video_tune = "-tune stillimage"
video_film_tune = "-tune grain"
; video_film_tune="-tune film"
verbose = "-hide_banner -loglevel warning"
audio_format = "wav"
fps = 25



; language = 'en'

[dimensions]
width_final = 1440
height_final = 1080


[video_format_upscale]
; codec = ffv1
; codec_options =
; pix_fmt = yuv444p12le

codec = h264
codec_options = "-preset slow -crf 15 -tune animation"
pix_fmt = yuv420p

; codec = ffv1
; codec_options =
; pix_fmt = yuv444p10le
