
[audio.fr]
source = k
precedemment = 2670:3746
episode = 3746:34115, fadeout=1:cos, silence=0.5
g_asuivre = 34118:34190
asuivre = 34190:34839, silence=0.5
g_documentaire =
    34853:34867
    34853:35106
documentaire = 35106:38798, silence=0.5


[audio.en]
source = f
precedemment = 2704:3782
episode = 3782:34154, fadeout=0.5:cos, silence=0.5
g_asuivre = 34155:34227
asuivre = 34227:34875, silence=0.5
g_documentaire =
    34890:34904
    34890:35142
documentaire = 35142:38838, silence=0.5


[video]
source = f
documentaire = fadeout=1.0


[scenes_episode.fr]
# Remove from 1st scene rather than scene no.20
# because no diff of avysnc
003 = count=41
