[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2701:3397
episode = 3441:33521
g_asuivre = 33640:33715
asuivre = 33715:34322
g_documentaire = 34361:34628
documentaire = 34629:38929


[shots_precedemment]
000 = 2701:3397
; 2798

[shots_episode]
000 = 3441:33521
; 3611

[shots_asuivre]
000 = 33715:34322
; 33756

[shots_documentaire]
000 = 34629:38929
