[deinterlace]
ffv1 = true
range = 33600:33700


; [filters_g_asuivre]
; default="""
;     avisynth:   deinterlace;
;     pytorch:    2x_LD-Anime_Skr_v1.0;
;     pytorch:    1x_HurrDeblur_SuperUltraCompact_nf24-nc8_244k_net_g;
;     python:     bilateralFilter=11:15:13;
;     python:     scale=0.5:bicubic;
;     pytorch:    realesr-animevideov3;
;     *python:    scale=0.5:bicubic;
;     """

; default="""
;     avisynth:   deinterlace;
;     *pytorch:    2x_LD-Anime_Skr_v1.0;
;     *pytorch:    1x_BeaverIt;
;     *python:    bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.5;
;     """



[chapters]
g_debut = 0:2658
precedemment = 2658:3373
episode = 3383:33602
g_asuivre = 33610:33684
asuivre = 33684:34328
g_documentaire = 34331:34597
documentaire = 34597:38846
g_fin = 38846:40825

[g_asuivre]
scenes=
    33659:33660

[offsets]
g_debut = 0:0
g_documentaire = 0:-139
g_fin = 0:170
g_asuivre = 0:0

