

[audio.fr]
source = k
precedemment = 2659:3387
episode = 3387:33571, fadeout=0.25:cos, silence=0.5
g_asuivre = 33578:33648
asuivre = 33648:34293, fadeout=0.25:cos, silence=0.5
g_reportage =
    34298:34565
reportage = 34565:38830, fadeout=0.25:cos, silence=0.5


[video]
source = k
precedemment  = 2660:3375
episode = 3390:-1
; g_asuivre =
asuivre = 33648:-1
; g_reportage =
reportage = 34564:38833, fadeout=1.0

