[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2703:3422
episode = 3439:33540
g_asuivre = 33621:33694
asuivre = 33694:34329
g_documentaire = 34333:34600
documentaire = 34601:38870


[shots_precedemment]
000 = 2703:3422
; 2730

[shots_episode]
000 = 3439:33540
; 3662

[shots_asuivre]
000 = 33694:34329
; 33798

[shots_documentaire]
000 = 34601:38870

