
[audio.fr]
source = k
precedemment = 2663:3389
episode = 3389:33600, fadeout=0.25:cos, silence=0.5
g_asuivre = 33604:33693
asuivre = 33693:34325, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34325:34592
documentaire = 34592:38876, fadeout=0.25:cos, silence=0.5


[video]
source = k
precedemment  = 2664:3377
episode = 3388:-1
; g_asuivre =
asuivre = 33693:-1
; g_documentaire =
documentaire = 34594:38867, fadeout=1.0

