[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2699:3417
episode = 3436:33552
g_asuivre = 33656:33731
asuivre = 33731:34363
g_documentaire = 34378:34645
documentaire = 34646:38795


[shots_precedemment]
000 = 2699:3417
; 2754

[shots_episode]
000 = 3436:33552
; 3821

[shots_asuivre]
000 = 33731:34363
; 33829

[shots_documentaire]
000 = 34646:38795

