[deinterlace]
ffv1 = true
range = 0:-1

[filters_g_debut]
default="""
    deinterlace: qtgmc;
    upscale:
        LDVDeNoise_35mm_Compact, scunet_color_real_gan;
    """
# LDVDeNoise_35mm_Compact, scunet_color_real_gan;
# scunet_color_real_gan, 2x-DigitalFilmV5-Lite;
# scunet_color_real_gan, 2x_Ani4Kv2_G6i2_Compact_107500;
# scunet_color_real_gan, 2x_LD-Anime_Skr_v1.0;


# scunet_color_real_gan, 4xNomos2_realplksr_dysample:cuda:fp16;
# scunet_color_real_gan, 2x_AniSD_DC_RealPLKSR_115K
# scunet_color_real_gan, 2x_AniScale2_ESRGAN_i16_110K

014 = """
    deinterlace: qtgmc;
    upscale:
        2x_AniSD_DC_RealPLKSR_115K;
    """


[filters_g_fin]
default="""
    deinterlace: qtgmc;
    upscale:
        LDVDeNoise_35mm_Compact, scunet_color_real_gan;
    """



[chapters]
g_debut = 0:3323
g_fin = 3324:5570



[scenes_g_debut]
000 = 0,
001 = 674
002 = 830
003 = 960
004 = 1100
005 = 1310
006 = 1577
007 = 1797
008 = 1926
009 = 2097
010 = 2182
011 = 2256
012 = 2297
013 = 2499
014 = 2543
015 = 2694
016 = 2746
017 = 2949
018 = 3278:3322, filters=014


[scenes_g_fin]
000 = 3324
001 = 3629
002 = 3651
003 = 4124
004 = 4174
005 = 4199
006 = 4222
007 = 4301
008 = 4343
009 = 4632
010 = 4692
011 = 4999
012 = 5316:5570








