
[audio.fr]
source = k
precedemment = 2665:3398
episode = 3398:33628, fadeout=0.50:cos, silence=0.5
g_asuivre = 33628:33697
asuivre = 33697:34349, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34349:34620
documentaire = 34609:38856, fadeout=0.50:cos, silence=0.5


[video]
source = k
precedemment  = 2666:3378
episode = 3389:-1
; g_asuivre =
asuivre = 33697:-1
;g_documentaire =
documentaire = 34610:38858, fadeout=1.0

