
[audio.fr]
source = k
precedemment = 2665:3398
episode = 3398:33628, fadeout=0.50:cos, silence=0.5
g_asuivre = 33628:33697
asuivre = 33697:34349, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34349:34620
documentaire = 34609:38856, fadeout=0.50:cos, silence=0.5


[audio.en]
source = f
# random values just to extract audio track
precedemment = 2704:3431
episode = 3431:33663, fadeout=0.25:cos, silence=0.5
g_asuivre = 33664:33735
asuivre = 33735:34385, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34399:34413
    34399:34413
    34399:34413
    34428:34665
documentaire = 34665:38911, fadeout=0.5:cos, silence=0.5


[video]
source = f


; [video.fr]
; source = k
; precedemment  = 2666:3378
; episode = 3389:-1
; ; g_asuivre =
; asuivre = 33697:-1
; ;g_documentaire =
; documentaire = 34610:38858, fadeout=1.0

