
[deinterlace]
ffv1 = true
range = 0:2800


[filters_g_debut]
; default="""
;     avisynth:  deinterlace;
;     *python:     deshake;
;     *animesr:    AnimeSR_v2;
;     *pytorch:    1x_BeaverIt;
;     *python:    bilateralFilter=11:15:13,
;                 unsharp_mask=2:0.3;
;     *python:     deshake;
;     *ffmpeg:     hqdn3d=2;
;     """
default="""
    deinterlace: qtgmc;
    upscale: A:\ml_models\2x-LD-Anime-Compact.pth;
    final: hqdn3d=3;
    """

02="""
    avisynth:   deinterlace;
    *python:    deshake;
    *animesr:   AnimeSR_v2;
    *pytorch:    1x_BeaverIt;
    *python:    bilateralFilter=11:15:13,
                unsharp_mask=2:0.3;
    *python:    deshake;
    *ffmpeg:    hqdn3d=3;
    *python:    unsharp_mask=2:0.3;
    """

03="""
    avisynth:   deinterlace;
    *scunet:    gan;
    pytorch:    1x_HurrDeblur_SuperUltraCompact_nf24-nc8_244k_net_g;
    *python:    deshake;
    *real_cugan:  s=2,n=3;
    """

13="""
    avisynth:   deinterlace;
    *python:  deshake;
    *real_cugan:  s=2,n=3;
    *pytorch:    1x_BeaverIt;
    *python:    bilateralFilter=11:15:13,
                unsharp_mask=2:0.3;
    *python:    deshake;
    *ffmpeg:    hqdn3d=3;
    *python:    unsharp_mask=2:0.3;
    """

14="""
    avisynth:   deinterlace;
    *python:    deshake;
    *real_cugan:  s=2,n=3;
    *pytorch:    1x_BeaverIt;
    *python:    bilateralFilter=11:15:13,
                unsharp_mask=2:0.3;
    *python:    deshake;
    *ffmpeg:    hqdn3d=3;
    *python:    unsharp_mask=2:0.3;
    """


; id_upscale=3
; upscale="realcugan-ncnn-vulkan=s=2:n=3"
; ; upscale="realcugan-ncnn-vulkan=g=-1:s=2:n=3"

; id_denoise=3
; denoise="""
;     unsharp_mask=3:0.5,
;     bilateralFilter=11:15:15,
;     """


; default="""
;     avisynth:  deinterlace;
;     null;
;     real_cugan:    s=2,n=3;
;     *python:     unsharp_mask=3:0.6;
;     *python: deshake;
;     """

# default="""
#     avisynth:  deinterlace;
#     null;
#     real_cugan:    s=2,n=3;
#     *pytorch:    1x_BeaverIt;
#     *python:    bilateralFilter=11:15:13,
#                 unsharp_mask=2:0.3;
#     *python:  deshake;
#     """

; id_upscale=20
; upscale="""
;     scale=width_upscale:height_upscale:lanczos
;     """

; id_denoise=25
; denoise="""
;     fastNlMeansDenoisingColored=5:5:7:13,
;     bilateralFilter=9:15:15,
;     edge_sharpen_sobel=3:0.15,
;     unsharp_mask=3:0.4
;     """

; id_sharpen=20
; sharpen="""
;     morphologyEx=MORPH_RECT:3:1,
;     fastNlMeansDenoisingColored=3:3:5:7,
;     unsharp_mask=2:1.3,
;     morphologyEx=MORPH_RECT:3:1,
;     bilateralFilter=11:15:13
;     """


[chapters]
g_debut = 0:2670


[offsets]
; g_debut = 0:2
g_documentaire = 0:2037


[scenes_g_debut]
000 = 0
001 = 650
002 = 800
003 = 924
004 = 1088
005 = 1299
006 = 1510
007 = 1634
008 = 1798
009 = 1879
010 = 1916
011 = 1957
012 = 2005
013 = 2200
014 = 2523:2630
