[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut =  0:2665
precedemment = 2702:3419
episode = 3433:33603
g_asuivre = 33618:33692
asuivre = 33692:34269
g_documentaire = 34334:34600
documentaire = 34601:38918


[shots_precedemment]
000 = 2702:3419
; 2758

[shots_episode]
000 = 3433:33603
; 3900

[shots_asuivre]
000 = 33692:34269
; 33744

[shots_documentaire]
000 = 34601:38918

