

[audio.fr]
source = k
precedemment = 2663:3390
episode = 3390:33577, fadeout=0.50:cos, silence=0.5
g_asuivre = 33577:33649
asuivre = 33649:34298, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34325:34339
    34325:34339
    34325:34564
documentaire = 34564:38874, fadeout=0.25:cos, silence=0.5


[audio.en]
source = f
# random values to be able to extract audio
precedemment = 2700:3400
episode = 3400:35000, silence=0.5
g_asuivre = 35000:35100
asuivre = 35100:35700, silence=0.5
g_documentaire =
    35700:36000
documentaire = 36000:39000, silence=0.5


[video]
source = f

; [video.fr]
; source = k
; precedemment  = 2663:3382
; episode = 3389:-1
; ; g_asuivre =
; asuivre = 33649:-1
; ; g_documentaire =
; documentaire = 34565:38882, fadeout=1.0

