[deinterlace]
ffv1 = true
range = 0:-1


[filters_precedemment]
default="""
    *avisynth:   deinterlace;
    """


[filters_episode]
default="""
    *avisynth:   deinterlace;
    """


[filters_asuivre]
default="""
    *avisynth:   deinterlace;
    """


[filters_documentaire]
default="""
    *avisynth:   deinterlace;
    """


[parts]
g_debut = 0:2665
precedemment = 2703:3422
episode = 3435:33585
g_asuivre = 33615:33690
asuivre = 33690:34325
g_documentaire = 34336:34603
documentaire = 34604:38905


[shots_precedemment]
000 = 2703:3422
; 2835

[shots_episode]
000 = 3435:33585
; 3667

[shots_asuivre]
000 = 33690:34325
; 33784

[shots_documentaire]
000 = 34604:38905
