[audio.fr]
source = k
precedemment = 2668:3392
episode = 3392:33743, silence=0.5
g_asuivre = 33750:33822
asuivre = 33822:34470, fadeout=0.25:cos, silence=0.5
g_documentaire =
    34470:34738
documentaire = 34738:38864, fadeout=0.25:cos, silence=0.5


[video]
source = k
precedemment = 2670:3382
episode = 3400:-1
; g_asuivre =
asuivre = 33822:-1
;g_documentaire =
documentaire = 34736:38865, fadeout=1.0


